### ISSUE TITLE
Flameshot gui doesnt start via terminal command or shortcut (prtsc)

### ISSUE THREAD

**Issue by lxwulf** [flameshot-org/flameshot#1186]
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**
Flameshot gui doesnt work every other option works fullscreen shot works also but not the retangle modus.

**To Reproduce**
Install flameshot on Fedora 33 KDE Version fully updated

**Expected behavior**
Starting flameshot gui when i press prtsc

**System Information**
Fedora 33
Kernel 5.9.13-200
DE: Plasma 5.20.4 (Wayland)
WM: kwin

Greets

LxWulf

**Comment by ipesanz** [comment]
Same here, in a recently installed Fedora 33.

**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.12.3

**To Reproduce**
Install flameshot on Fedora 33 with: sudo snap install flameshot

**System Information**
Kernel: 5.9.15-200.fc33.x86_64
Wayland

**Comment by borgmanJeremy** [comment]
@lxwulf Did you also install via snap?

**Comment by lxwulf** [comment]
Hey, @borgmanJeremy I installed it via dnf which install the rpm package.

Name         : flameshot
Version      : 0.8.5
Release      : 1.fc33
Architecture : x86_64
Size         : 1.2 M
Source       : flameshot-0.8.5-1.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : Powerful and simple to use screenshot software
URL          : https://github.com/lupoDharkael/flameshot
License      : GPLv3+ and ASL 2.0 and GPLv2 and LGPLv3 and Free Art
Description  : Powerful and simple to use screenshot software with built-in editor with advanced features.

**Comment by lxwulf** [comment]
Is here any update why it doesn't work any more? @borgmanJeremy Can i help with any information? It would be very nice when we can fix this I really love flameshot its such very handy tool!

Greets LxWulf

**Comment by maikokuppe** [comment]
Same here.

But it suddenly started working after I started `flameshot gui` via `dmenu`. After this, `flameshot gui` worked both via command line and via shortcut :shrug: 

I installed it via snap.

```
~ > flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.12.3
```

**Comment by lxwulf** [comment]
Sadly this doesn't work on my system I hope we find a fix....don't want to hop to another tool...

**Comment by borgmanJeremy** [comment]
@lxwulf I see you are on the wayland version of plasma. Can you try forcing flameshot to use XWayland per: #675

**Comment by lxwulf** [comment]
Sadly this doesn't help me =(....

**Comment by borgmanJeremy** [comment]
@lxwulf Okay 0.9 RC1 improves wayland support. It works fine for me now on Fedora 33 Gnome. I didn't try fedora33 with KDE Wayland since KDE wayland really isn't properly working yet.

If it still does not work I highly suspect a wayland KWIN issue since it works fine on gnome.

**Comment by lxwulf** [comment]
Yes i think it too. The coincidence want it that my system completely failed. So now i changed to gnome which have so much more a better experience with multi monitor setup and wayland. I didn't test flameshot until now but i want it to do. I comment here in the next few days if something is wrong.

**Comment by lxwulf** [comment]
Sadly it doesn't work properly on Fedora (33) with default Gnome DE und Wayland WM. I can start but it when copy the prtsc it has some distortion in it.

![s](https://user-images.githubusercontent.com/44492381/109524209-863e6180-7ab0-11eb-8874-1388b486d324.png)

Also, it has problems with multi monitor setup. I have it only on my left screen instead of my main monitor on the right....

**Comment by lxwulf** [comment]
On the newest update it works so far very good even on a multi-monitor setup. The only thing is that I have no tray icon even I installed the preferred extension for gnome. But technically it works now.

**Comment by mmahmoudian** [comment]
@lxwulf do you see other apps' icons in the tray and Flameshot is the only one missing, or you don't see anything in the tray?

**Comment by lxwulf** [comment]
Flameshot is the only one which im missing others works like discord, telegram, signal or joplin as example.

**Comment by mmahmoudian** [comment]
@lxwulf  I believe your issue is identical to #1280 .  Based on that thread, it seems that in 0.9 the issue is resolved. Would you please confirm:
1. your Flameshot version (if it is older than 0.9.0 please update)
2. the method you have installed Flameshot through (dnf repo, Flatpak, Snap, dnf manual rpm, ...)
3. if the issue still persists

**Comment by maikokuppe** [comment]
Using `v0.9.0` installed via `snap` I still have the same issue. I'm still using the workaround to run `flameshot gui` via `dmenu` once, so I can use cli and shortcuts after that.

**Comment by lxwulf** [comment]
Hey @mmahmoudian so far my answers to you:

1. yes the newest version --> 0.9.0
2. dnf repo from fedora
3. yes issue is still persists, i have no tray icon

**Comment by lxwulf** [comment]
I don't know why but however my tray icon does appear now so for me, it is solved sadly without much information what the problem triggered...

Greets LxWulf

![image](https://user-images.githubusercontent.com/44492381/111064119-98f26680-84b2-11eb-8335-e85ba4301f98.png)

**Comment by mmahmoudian** [comment]
@lxwulf now that it has been "solved" in mysterious way, let us know your Flameshot version. Perhaps and update of some kind have helped and I'm curious to know what

**Comment by lxwulf** [comment]
Hey @mmahmoudian 

Sorry, didn't want to just close it without any information given – but at that moment I didn't really know what the problem was. Retroperspective I would say it was my gnome overlay I had. It was an extension which I installed to have something like tiling window desktop environment. I think there was the issue.

I'm sorry that I did not give more or specific information, in future I would keep that in mind.

**Comment by mmahmoudian** [comment]
@lxwulf no worries and there is absolutely nothing to be sorry about. I'm just curious because it might be a rare bug and would be nice to know what caused it. 😊

Thanks for reporting the bug initially and thanks for keeping us updated about the miraculous fixed situation. 👍🏼
