### ISSUE TITLE
macOS flameshot only works on primary screen when there are multiple monitors in the same Space

### ISSUE THREAD

**Issue by numeratorjik** [flameshot-org/flameshot#1258]
**Flameshot version**
265e42c7b08e2296a55061b7bde61e0d56dbac3c on macOS Catalina

**Describe the bug**
If you have two monitors, and they're both in the same Space, and you tell Flameshot to take a screenshot, the secondary monitor goes black and you can only take a screenshot of something running on the primary monitor.

**To Reproduce**
In Mission Control, disable the option that creates different Spaces for your two monitors. Log out and log back in. Launch Flameshot. Tell it to take a screenshot.

**Expected behavior**
It should be possible to take a screenshot from either monitor.

**System Information**
macOS catalina

**Comment by numeratorjik** [comment]
P.S. While this is annoying, I definitely want to say *thank you so much* for making Flameshot work on macOS!

**Comment by thepurple** [comment]
Please check it again, there're a lot of fixes for MacOS (especially for multiple displays) in the latest version (source code, not in the binaries yet).

**Comment by numeratorjik** [comment]
Problem still exists in current source code.

**Comment by thepurple** [comment]
Got it, I didn't read carefully and didn't check exactly your case.
If I understand you well, there is not menu in such configuration on secondary display and you cannot click on Flameshot icon and select "Take screenshot" on non-primary screen. I'll think about how to handle it.
For now you still have an option to use hotkeys. Move mouse pointer to the required display and press Command+Option+Shift+4.

**Comment by numeratorjik** [comment]
Hotkey does not help. The behavior is the same when I hit the hot key. It's always the primary screen for the space that is active after hitting the hot key, regardless of which screen my mouse is on when I hit it.

**Comment by thepurple** [comment]
I'll try to find somewhere Catalina, on a BigSur hotkey works fine for the described case.

I know about similar issue (capture primary screen only) on a systems with multiple displays after sleeping mode or connecting/disconnecting displays, which is reproducible just sometimes and on some systems, Flameshot restarting helps.

But this case is another one.

**Comment by bboles** [comment]
I am seeing the same behavior as @numeratorjik described but the `Command+Option+Shift+4` hotkey works for me on either monitor.  FWIW I am using 2 external displays connected to a 2019 MacBook Pro.

**Comment by numeratorjik** [comment]
New information: `Command+Option+Shift+4` doesn't work for me when I use a DisplayLink dock with two monitors connected to it, with one of the monitors mirroring the laptop's built-in display and the second monitor extending. However, it _does_ work for me when I plug two monitors separately into my MacBook and there's no mirroring, i.e., the two monitors and the built-in display are all showing different content.

**Comment by bboles** [comment]
I still have the same hardware setup mentioned in [my previous comment](https://github.com/flameshot-org/flameshot/issues/1258#issuecomment-801166357) but have upgraded to Big Sur.  Now the `Command+Option+Shift+4` hotkey behaves the same way as clicking 'Take Screenshot' in the menu: a new blank desktop seems to be created on the primary display and the secondary display is blank.

**Comment by numeratorjik** [comment]
Interestingly, I see the above behavior as well, but if I quit from Flameshot and restart it and then immediately use the hotkey while a window on my second screen is focused, the right thing happens.
Just to be clear, I have both screens in the same workspace.

**Comment by bboles** [comment]
I have both screens in the same workspace as well.

**Comment by KyleStiers** [comment]
Any fix on this? I'm on macOS BigSur (M1 macbook pro) and use a single mirrored monitor and when attempt to use flameshot it goes to a screen where I only see my background image (Desktop) and nothing else. Using version 0.10.1 of flameshot.

**Comment by thepurple** [comment]
Try please to restart a Flameshot and use hotkeys.
In some cases, after going to sleep or connecting/disconnecting an external monitor, the Qt library may lose other displays and I didn't find a way to refresh displays list. 
Possibly it is fixed in the Qt6 (didn't check it yet), but have no time to migrate to Qt6 now.

**Comment by KyleStiers** [comment]
Using the `shift+alt+cmd+4` hotkey? That doesn't work. Sorry should've mentioned I tried that when seeing it suggested above.

**Comment by nanggo** [comment]
On my macbook pro 16" also doesn't work multiple desktops.

When I using hotkey for capturing, flameshots start capture on new desktop (empty screen).

**Comment by thepurple** [comment]
Unfortunately, I don't have a MacBook right now, I'll try to reproduce it when it appears.
Actually Flameshot doesn't detect the active screen in MacBook terms, in Qt5 there is no such option. The active screen for Flameshot is the display where the mouse cursor is placed in.

**Comment by Rihcus** [comment]
> Try please to restart a Flameshot and use hotkeys. In some cases, after going to sleep or connecting/disconnecting an external monitor, the Qt library may lose other displays and I didn't find a way to refresh displays list. Possibly it is fixed in the Qt6 (didn't check it yet), but have no time to migrate to Qt6 now.

This seems to work. If I connect to an external moniter and had flameshot open prior then I run into the primary display issue. However after restarting I have no issues even if I disconect and reconnect the external moniter. I guess the cavoit is this may break if another external moniter is connected or flameshot is restared without an external moniter.  Using MBP 2016 Catelina.

**Comment by nanggo** [comment]
@thepurple My issue resolved that I reinstall flameshot.

**Comment by thepurple** [comment]
@nanggo thanks for letting me know.

**Comment by rylincoln** [comment]
I had this issue where when I tried to take a screenshot it would swipe over to a new blank virtual desktop ... I had to go set permissions, then restart the app and it was fixed.  Not 100% if the permissions were the problem.  ymmv :)
![image](https://user-images.githubusercontent.com/741887/144525677-55fab64d-b06e-492b-96b9-98ee14bf61f4.png)

**Comment by cellscripts** [comment]
> I had this issue where when I tried to take a screenshot it would swipe over to a new blank virtual desktop ... I had to go set permissions, then restart the app and it was fixed. Not 100% if the permissions were the problem. ymmv :) ![image](https://user-images.githubusercontent.com/741887/144525677-55fab64d-b06e-492b-96b9-98ee14bf61f4.png)

Perfect solution.

**Comment by bboles** [comment]
This issue is still present in version 0.10.2.  @borgmanJeremy is there some reason this was closed?

**Comment by borgmanJeremy** [comment]
Unless I'm mistaken it's just a permissions issue.

**Comment by cellscripts** [comment]
It's just a permission issue in Mac

**Comment by bboles** [comment]
I also was able to fix by uninstalling, installing again and selecting flameshot again in the `Screen Recording` section.  For anyone else that may come across this issue in MacOS, depending on how you have Spaces configured in Mission Control you may only be able to activate flameshot on a particular external display by using the `shift+alt+cmd+4` hotkey.  Otherwise, flameshot will only activate on the main display if you click "Take Screenshot" from the application menu.

Thanks for the clarification @borgmanJeremy and @cellscripts !

**Comment by rodrigolopezguerra** [comment]
I va set permissions correctly , and still having the issue.  What i am missing? 
![WhatsApp Image 2022-03-18 at 08 45 16](https://user-images.githubusercontent.com/3514141/158997569-061a4e46-eb55-400b-92b6-818a184a3172.jpeg)

![2022-03-18_08-46](https://user-images.githubusercontent.com/3514141/158997668-b80a2b1c-9a2e-405e-9e32-17f51d1d2d2a.jpeg)

Issue seems to match this description : "Try please to restart a Flameshot and use hotkeys. In some cases, after going to sleep or connecting/disconnecting an external monitor, the Qt library may lose other displays and I didn't find a way to refresh displays list. Possibly it is fixed in the Qt6 (didn't check it yet), but have no time to migrate to Qt6 now." for behaviour at least. If restarted , stats working fine again. 

thanks!

**Comment by Pixel-Jack** [comment]
After an update, I had to remove the line stated in the above screenshots, then add it again and restart the app as asked by the MacOS. Now it works 👍 Thanks for this excellent tool

**Comment by mstojanovic-upw** [comment]
I managed to change screen focus by disabling screen recording permissions in macOS Security - Preferences ... and than enabled it again. With this, I changed focus on another display that I use more often—but still not working on both displays.

**Comment by Goralive** [comment]
> After an update, I had to remove the line stated in the above screenshots, then add it again and restart the app as asked by the MacOS. Now it works 👍 Thanks for this excellent tool

Did it also and it works for me. But from time to time after the mac goes to sleep mode the functionality starts not working you need to just restart the app and it should work

**Comment by AymericFenschSequoiasoft** [comment]
it doesn't work evant after reinstall, delete from screen recording permissions, and reboot/restart application

**Comment by AymericFenschSequoiasoft** [comment]
> 

I don't have the shift+alt+cmd+4 hotkey on my MacOS.

**Comment by rewanthtammana** [comment]
Thanks, @rylincoln for https://github.com/flameshot-org/flameshot/issues/1258#issuecomment-985119655. It's helpful

**Comment by sancmk** [comment]
> I had this issue where when I tried to take a screenshot it would swipe over to a new blank virtual desktop ... I had to go set permissions, then restart the app and it was fixed. Not 100% if the permissions were the problem. ymmv :) ![image](https://user-images.githubusercontent.com/741887/144525677-55fab64d-b06e-492b-96b9-98ee14bf61f4.png)

It worked here. Thank you.

**Comment by AlexanderMakarov** [comment]
On Macbook Pro 2019 I'm fixing it with "Quit" in Flameshot and launching it again. Fortunately, this issue is rarely reproduced and most times it starts capture on the "current focus" monitor.

**Comment by FlahDev** [comment]
I just revoked flameshot screen record permission, stopped the app, give the permission again, and stopped and reopen the app again.

Now everything works fine  ˆ ˆ

**Comment by FlahDev** [comment]
I just revoked flameshot screen record permission, stopped the app, give the permission again, and stopped and reopen the app again.

Now everything works fine  ˆ ˆ

**Comment by tfactor2** [comment]
It's reproduced on reconnecting screens while the app is running.

**Comment by 4mp3d** [comment]
Everytime I reconnect mointors or wake up from sleep it seems to lose the other monitors, I just quit and relaunch and it solves it.
