### ISSUE TITLE
Custom color is always black

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1333]
**Flameshot version**
Current Git version (commit 67952f06abb7261b5862428f2b1ee76fd7b008af)

**Describe the bug**
There is a new color button in the current version Git version, this button automatically opens the Tool Settings and you can select a custom color with the Color Picker. However, the color is always black in the beginning, no matter what color the Color Picker shows.

**To Reproduce**
* Select filled rectangle or another tool, then press right mouse button
* Go to custom color, the color is black
* Select another color than black in the Color Picker
* Press right mouse button and go to custom color, the selected color switch to black again

**Expected behavior**
The new color button should show the last selected color in the color picker and not always change to black. 

**System Information**
Arch Linux, Xfce

![Unbenannt](https://user-images.githubusercontent.com/39984895/108104492-a838ec80-708b-11eb-9302-3c46e95329b1.png)

**Comment by borgmanJeremy** [comment]
Thanks for testing!

Haven't implemented a fix yet but I think it will involve adding a slot to colorpicker.h / colorpicker.cpp. This slot should get activated by  a signal in sidepandelwidget when the color changes.

**Comment by kpcee** [comment]
Great! But I have found another small bug, if you select a color and the color picker is displayed, the color is highlighted there. But if you go to Custom Color, the Color Picker is scrolled in sideways every time.

**Comment by thepurple** [comment]
Please check it again now. I cannot reproduce it or didn't get what you meant.
There was a similar bug with grabbing a color, I fixed it. 
It may have had the same root cause and possibly is already fixed.

**Comment by kpcee** [comment]
The bug is still present (commit 16fd3b2915829ccb550a023d7b829b7a46beebde). 

To test:
* Take a screenshot
* Select a paint tool e.g. filled rectangle
* Right click, go to Custom Color and choose a custom color in the color picker
* Paint a rectangle, it has the custom color
* Right click, select Custom Color. The color picker opens, but don't select anything. The color picker shows your last selected color. Paint another rectangle, it is now black and not what was selected before or what the color picker shows.

**Comment by thepurple** [comment]
Got it, thanks for good explanations.

**Comment by thepurple** [comment]
Fix: https://github.com/flameshot-org/flameshot/pull/1360

**Comment by kpcee** [comment]
I tested it with the current Git version (commit 5b0bb501dc513f16e93a6d72e06a222a2da6c404 ) and it works, but differently than expected. For example, if you select a custom color, e.g. bluish and then select the button for the default color yellow and then go back to custom color, the selected color is yellow instead of bluish. If that's the way it's supposed to be, then okay, but I would expect bluish to be the default, since that was the last selected custom color.

**Comment by borgmanJeremy** [comment]
Now that the main branch lets users define custom colors through the GUI I am going to close this.
