### ISSUE TITLE
flameshot gui command in wrong screen

### ISSUE THREAD

**Issue by mokkin** [flameshot-org/flameshot#1335]
**Flameshot version**

0.9.0 rc1

**Describe the bug**

I'm using `flameshot gut` via keyboard shortcuts and I have three screens. Since my upgrade to the recent version it is always choosing the third screen. Before upgrading the active screen or window was selected.

**To Reproduce**

**Expected behavior**

Select active screen/window.

**System Information**

Ubuntu 20.04

**Comment by borgmanJeremy** [comment]
Can you try using the master branch? I merged some fixes that might fix this.

**Comment by durka** [comment]
I am also experiencing this bug on 20.04 and it is not fixed on master.

The bug exists at least all the way back to 0.8.0. Back in 0.6.0 the screenshot covered both screens, which is better.

**Comment by mmahmoudian** [comment]
I don't have access to Ubuntu machine anymore. But I cannot reproduce this on Manjaro with 3 monitors. I will un-assign myself.

**Comment by Vir18** [comment]
Hello there, The same issue observed on Windows 7 64-bit. I use two monitors. If user made s screenshot the secondary screen, the capture will be placed on primary monitor. As a result, each new screenshot capture was always selected on primary monitor, even if previous one has been taken on second screen. It was expected that a new capture was placed on the same place: on secondary monitor. Please refer to the images below. Thanks for your time!

First image is a first screenshot capture. Second image described a bug itself, when user wanted to make a the next screenshot.
![1st step](https://user-images.githubusercontent.com/46133804/189430656-f77927d8-56b8-4708-afd2-53809d716e98.png)
![2nd step](https://user-images.githubusercontent.com/46133804/189430673-06d3cd86-d3aa-4c4b-9c4c-bbabf7bdf31f.png)

**Comment by mmahmoudian** [comment]
This should have been fixed with #4498 
If you can, try compiling from the master branch and let us know is this issue still persists. I'm going to close this for now, but if the issue persists, we will re-open it.
