### ISSUE TITLE
Upload animation freezes 

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1503]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
The upload animation freezes and this causes the users to panic (#1501). Also, to my surprise (I repeated this 3 times and got the same exact result), the clock on the screen also stops working for half of the duration of uploading process!

I suggest the Latest Uploads window opens after the upload is completed.

![Peek 2021-03-22 15-20](https://user-images.githubusercontent.com/390889/111996686-f4f86300-8b22-11eb-8a1a-5c5941549fc4.gif)

**To Reproduce**
1. `flameshot gui`
2. select the region
3. click on upload to Imgur
4. the animation freezes and users panic

**Expected behavior**

Smooth animation.

**System Information**
>```
> System:
>     Host: hostname Kernel: 5.9.16-1-MANJARO x86_64 bits: 64
>     Desktop: KDE Plasma 5.21.3 Distro: Manjaro Linux
> Graphics:
>     Device-1: Intel driver: i915 v: kernel
>     Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel
>     Display: x11 server: X.Org 1.20.10 driver: loaded: amdgpu,ati,intel
>     unloaded: modesetting resolution: 1: 1920x1080~60Hz 2: 1080x1920~60Hz
>     OpenGL: renderer: AMD Radeon Pro WX 3200 Series (POLARIS12 DRM 3.39.0
>     5.9.16-1-MANJARO LLVM 11.1.0)
>     v: 4.6 Mesa 20.3.4
>```

**Comment by borgmanJeremy** [comment]
@mmahmoudian this should be fixed on the master branch. Can you test that? I really need to get a point release out.

**Comment by mmahmoudian** [comment]
I tried it with the AppImage of #1526 and got this:

![image](https://user-images.githubusercontent.com/390889/113427330-80081180-93dd-11eb-91fd-4cb83d1b73be.png)

I then tried with AppImage of  #1524 (which is the master) and got the same exact error. I wonder if it has something to do with AppImage. Should I try to compile it locally?

**Comment by borgmanJeremy** [comment]
Yeah either build from source or do a cleanbuild from AUR. Looks like the app image is missing the SSL binaries

**Comment by giswqs** [comment]
I am having the same issue. Flameshot freezes for about 10 seconds when uploading GIF to imgur.com

![image](https://user-images.githubusercontent.com/5016453/113514639-e0ae6000-953d-11eb-9912-986aedaabb52.png)

**Comment by coozoo** [comment]
actually for me the same freeze happens every time when I'm trying to copy into clipboard, just in difference that all screen frozen
the only way for me to switch tty and kill flameshot
but in console it's the only stuff that I see

```bash
$ flameshot
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
Terminated
```
Sure terminate it's only after killing by hands
mine version flameshot-0.9.0-1.fc33.x86_64

**Comment by mmahmoudian** [comment]
@coozoo How many seconds should you wait until it unfreezes itself without you killing it?

**Comment by coozoo** [comment]
> @coozoo How many seconds should you wait until it unfreezes itself without you killing it?

Oh about 15 seconds and I thought that's all and nothing will happen.

So I've tried to wait more, few times. First one unfreeze after ~30 seconds. 2nd - after about ~45, one more time and it's about 50s 😕

**Comment by dausruddin** [comment]
Can confirm. Installed [flameshot](https://archlinux.org/packages/community/x86_64/flameshot/) and having the same issue as OP.
Uploaded files exist as suggested in https://github.com/flameshot-org/flameshot/issues/1501, but I wish there will be no freeze at all since it also freezes some parts of my desktop.

**Comment by mmahmoudian** [comment]
I just checked with the latest commit in master Flameshot v0.10.1 (203b5baa) and it seems this is resolved. At least it doers not happen anymore.

@dausruddin would you please check this as well

**Comment by dausruddin** [comment]
Sorry, a bit late. But I can confirm the issue is no more.

Thanks.

**Comment by OnkelTem** [comment]
Still persists on:

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
linux: 5.13.0-27-generic
ubuntu*: 20.04

Kubuntu actually.

**Comment by mmahmoudian** [comment]
@OnkelTem how have you installed Flameshot?

**Comment by mmahmoudian** [comment]
@borgmanJeremy I can confirm that it is again happening. @OnkelTem Thanks for reporting. I'm re-opening this.

> Flameshot v11.0.0 (1cc5a262)
> Compiled with Qt 5.15.2
> linux: 5.15.16-1-MANJARO
> manjaro: unknown

**Comment by borgmanJeremy** [comment]
Disable "Copy URL after upload" for now. The bug is related to a race condition between the clipboard and the system notification....again

**Comment by borgmanJeremy** [comment]
#2348 seems to fix it for me. Will merge after the CI finishes.

**Comment by big-mak** [comment]
Getting the same issue, it seems that copying is what breaks it - even from this screen "Copy URL" and "Image to Clipboard" both crash flameshot even though a message shows up copying was successful. Luckily "Open URL" works fine.
![image](https://user-images.githubusercontent.com/82375998/157124306-83ebefa9-e8f4-43a6-9546-e69edfbffd31.png)
![image](https://user-images.githubusercontent.com/82375998/157124586-b9eb0e68-81be-4b1f-9cc0-05529c13f4ff.png)
