### ISSUE TITLE
save the capture: filename empty

### ISSUE THREAD

**Issue by zappee** [flameshot-org/flameshot#1563]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.12.3

**Describe the bug**
When the screenshot is taken then I click on the `save the capture` button. Then the save file dialog appears but the filename is completely empty. I use the default filename configuration. 

**To Reproduce**
Take a screenshot, then I click on the `save the capture` button. Then the save file dialog appears but the filename is completely empty. I use the default filename configuration. 

**Expected behavior**
Pre-defined filename must appear in the file dialog.

**System Information**
Linux xxxx 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sonulohani** [comment]
Hi @zappee 
I am not able to reproduce this issue. Could you please confirm the commit hash you're using and the version of the flameshot.

**Comment by zappee** [comment]
I use Linux Mint 20
and Flameshot v0.9.0, Compiled with Qt 5.12.3

[Video to demonstrate the bug](https://youtu.be/S6ERLGeF-_M )

**Comment by Goblin80** [comment]
Can you try overriding the default filename from the filename editor?

![9c1d9b6e-b1c8-47fd-a7d1-bce13766a345](https://user-images.githubusercontent.com/1815268/115994110-f01d4800-a5d5-11eb-8904-28839aa289cf.png)

**Comment by zappee** [comment]
As you can see in the video I use a custom filename pattern.
I have changed it after I saw that the filename is empty.
But the custom did not help.

This is the pattern I use: `screenshot-%F_%H%M%S`

**Comment by Goblin80** [comment]
Can you please run flameshot from the terminal and show us the output? you should get additional logging information...

```bash
$ flameshot

QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

**Comment by zappee** [comment]
This is the log:

- start of the app
- then a screenshot was taken
- then tried to save it (the file name in the Save dialog empty)

```
$ flameshot
Qt: Session management error: Could not open network socket
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.793\" (uid=1000 pid=1109293 comm=\"/snap/flameshot/77/usr/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=7742 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.793\" (uid=1000 pid=1109293 comm=\"/snap/flameshot/77/usr/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=7742 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active

```

**Comment by Goblin80** [comment]
I am not 100% sure where the problem might be but consider trying out the following:

1. Switch desktop environments, maybe it's something has to do with gnome.
1. Don't install flameshot from the snap craft/store, use the `apt install flameshot`.*

\* Depending on your Ubuntu version, you might get a slightly older version (0.8.3).

**Comment by borgmanJeremy** [comment]
Can you post the output of
```
locale
```

Might be a duplicate of 1548

**Comment by zappee** [comment]
```
$ locale

LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_BE.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_BE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_BE.UTF-8
LC_NAME=de_BE.UTF-8
LC_ADDRESS=de_BE.UTF-8
LC_TELEPHONE=de_BE.UTF-8
LC_MEASUREMENT=de_BE.UTF-8
LC_IDENTIFICATION=de_BE.UTF-8
LC_ALL=

```

**Comment by zappee** [comment]
I deleted all tha date and time related variables from the filename pattern:

![image](https://user-images.githubusercontent.com/3851507/116308572-8ea8d500-a79f-11eb-9d2d-3636d31e4943.png)

But the result is the same: the filename text box is empty in the save dialog box.

**Comment by zappee** [comment]
I hope that this can help you to identify the bug better:

When I click on the `save the capture` button then the default path where the files save dialog points is always `/run/user/1000/doc/c09ca30c`.

Then I change the directory and type the `12345678.png` in the empty filename text box.
Then the file appears in the directory properly.


BUT,
If I give a filename without extension, like `abc` or `12345678` then the following file is created by the Flameshot:

`.xdp_12345678.1B4G30` or `.xdp_abc.Y87Y30`.

The file content is okay, but the filename is wrong.

Could you please fix this stupid issue?
This application is soo cool, but this bug makes it hard to use it.

**Comment by vslobodyan** [comment]
Fedora 34, Gnome 4, Flameshot 0.9
I confirm the problem described above.

**Comment by cjlewis999** [comment]
I also have this issue, v0.90. It may be of interest (and is a temporary workaround) that enabling 'save image after copy' in the general config tab will name the image as defined in the filename editor tab.

**Comment by horada** [comment]
I can confirm this issue on Fedora 34,  Cinnamon-4.8.6-5, flameshot-0.9.0-1.fc34.x86_64.

I also built version from current master (35a6d430c9) and the issue seems to be still there.

**Comment by nlpsuge** [comment]
I confirm this issue on Fedora 34, Gnome 40.

$ flameshot -v
Flameshot v0.10.0
Compiled with Qt 5.15.2

**Comment by gfrein** [comment]
I can confirm this for Fedora 34, Gnome 40.4.0 (Wayland).

```
$ flameshot -v
Flameshot v0.10.1
Compiled with Qt 5.15.2
```

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I tried switching to `en_US.UTF-8` completely and also replacing the default filename pattern with random letters, but the problem persists.

**Comment by shayakbanerjee99** [comment]
I can confirm this too, for Ubuntu 21.04 running Gnome on xorg

```$ flameshot -v
Flameshot v0.10.1
Compiled with Qt 5.12.3
```

```$ locale
LANG=en_US.UTF-8
LANGUAGE=en_IN:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=```

**Comment by vittorio-c** [comment]
Hello,

Still having this issue here.

Here are some logs:

**Start application from command line :**
```
flameshot
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: HighContrastInverse, HighContrast, Adwaita-HighContrastInverse, Adwaita-HighContrast, Adwaita-Dark, Adwaita, Windows, Fusion
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passe
```

**Select a region of the screen to capture, then press CTRL-S to save it as a file :**

```
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

The result is still empty file name.

---

Here are my informations : 

```
flameshot --version
Flameshot v0.10.2
Compiled with Qt 5.15.2
```
```
echo $XDG_SESSION_TYPE
x11
```
```
uname -a
Linux manjaro 5.14.21-2-MANJARO
```
```
GNOME 41.2
```

```
locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE=C
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Comment by vittorio-c** [comment]
By the way, the workaround mentionned by @cjlewis999  is indeed working (thank you to him) : 

- enable 'save image after copy' in the general config tab
- select your region of the screen to capture
- instead of saving the file directly (ctrl-S), copy it in your clipboard (ctrl-C)
- you'll have your file automatically saved with correct filename in the folder specified in the general config tab
- worth to note that you'll also have your clipboard overrided with the content of the image you just saved. Which makes this solution non optimal

Thanks for the good work

**Comment by mmahmoudian** [comment]
@vittorio-c we have had a major refactoring of the code and many similar issue has been fixed. Would you please check our new prerelease v11.0 and see if the issue still persists?

**Comment by nlpsuge** [comment]
@mmahmoudian 

I installed flameshot-11.0.rc1-1.fc34.x86_64.rpm, and tested.

And the issue still persists, the filename is empty.

BTW. When I press the shortcut to capture the screen, It pops up an error notification 'The configuration contains an error. Falling back to default'.

**Comment by mmahmoudian** [comment]
@nlpsuge to get to know what's wrong with your config file, right-click on the tray icon, then configure, and then from the top side of the window which tell you that there are errors, click on the button to open the log and see what's wrong. Fix those (or alternatively delete the config file from `~/.config/flameshot/flameshot.ini`, kill Flameshot and open it again) and see if this fixes the empty file name issue.

**Comment by nlpsuge** [comment]
@mmahmoudian 

I simply renamed `~/.config/flameshot/flameshot.ini`, killed Flameshot and open it again. Mentioned error is gone.

No luck. The file name is still empty.

**Comment by mmahmoudian** [comment]
Then please do [as asked above](https://github.com/flameshot-org/flameshot/issues/1563#issuecomment-905869718):

> Everyone confirming this issue needs to post thier locale settings for us to make any sense of the problem.

**Comment by nlpsuge** [comment]
@mmahmoudian 
``` shell
$ locale
LANG=en_NZ.UTF-8
LC_CTYPE="en_NZ.UTF-8"
LC_NUMERIC="en_NZ.UTF-8"
LC_TIME="en_NZ.UTF-8"
LC_COLLATE="en_NZ.UTF-8"
LC_MONETARY="en_NZ.UTF-8"
LC_MESSAGES="en_NZ.UTF-8"
LC_PAPER="en_NZ.UTF-8"
LC_NAME="en_NZ.UTF-8"
LC_ADDRESS="en_NZ.UTF-8"
LC_TELEPHONE="en_NZ.UTF-8"
LC_MEASUREMENT="en_NZ.UTF-8"
LC_IDENTIFICATION="en_NZ.UTF-8"
LC_ALL=
```

**Comment by borgmanJeremy** [comment]
Digging through this I think the original issue was present in the snap package which was resolved yesterday with version 11.

**Comment by gfrein** [comment]
Still not working for me on Fedora 35, GNOME 41.3 (Wayland).

I tried both the rpm from the Fedora repos (v11.0.0) and the flatpak from Flathub (v11.0.0). Deleting the config folder (`~/.config/flameshot/`) didn't help either. Filename is still empty.

```
$ flameshot -v
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
```

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by nlpsuge** [comment]
Still not working for me too on Fedora 35, GNOME 41.3 (X11).
```
$ flameshot -v
Flameshot v11.0.0 ()
Compiled with Qt 5.15.2
```

**Comment by mmahmoudian** [comment]
@borgmanJeremy do you have a VM to test this? If not I can spin up one and test it tomorrow

**Comment by CVirus** [comment]
Still seeing this with v11.0.0 installed via snap.

**Comment by brennoflavio** [comment]
I'm also seeing this issue. I created Issue #2455 that seems to be duplicate of this. I don't know if I should close that as this one is closed already.
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by madhur** [comment]
I am also seeing the same issue 

```
Flameshot v12.0.0 ()
Compiled with Qt 5.15.5
linux: 5.16.2-1.el8.elrepo.x86_64
org.kde.Platform: 5.15-21.08
```

**Comment by HongYue1** [comment]
I'm on gnome 43 Fedora 37 and I had this issue, but there is a solution, if you enable "save to fixed path" option, it will be saved normally with the right name.
