### ISSUE TITLE
files saved in /var/run/user/1000/doc/{var} instead of /home/user/Pictures

### ISSUE THREAD

**Issue by sliddjur** [flameshot-org/flameshot#1637]
**Flameshot version**
flameshot --version
Flameshot v0.10.0
Compiled with Qt 5.12.3

Installed from snap store in Ubuntu 20.04

**Describe the bug**
When I take a screenshot, press ctrl+s to save, it doesnt save in my selected location, instead it defaults to /var/run/user/1000/doc/....

![image](https://user-images.githubusercontent.com/10002057/119102734-a54af080-ba1a-11eb-9655-0223219f6b51.png)

**To Reproduce**
- Take screenshot
- Press ctrl+s to save
- change dir to your home dir /home/user/Pictures/ (default cannot easily be changed as described in https://github.com/flameshot-org/flameshot/issues/1608 )
- type a file name you want.
Gnome now gives me a notificiation 

**Expected behavior**
I expected it to save file in dir that I specifically chose `/home/user/Pictures/`

**System Information**
Ubuntu 20.04
Flameshot from snap store

**Comment by mmahmoudian** [comment]
Yeap, this is a snap issue. I think it once happened in 0.8.5 once. I think @ZetaoYang or @borgmanJeremy had a quick solve for it.

**Comment by sliddjur** [comment]
I noticed some odd behaviour. 
If I save file in my `~/Pictures/` dir with name `screenshot` - then the file is actually saved into `/run/user/1000/doc/...`
If I save file in my `~/Pictures/` dir with name `screenshot.png` <- notice file extension in name, then the file is saved in my `~/Pictures` directory. However, the notification in Gnome3 is still saying file was saved under `/run/...`

**Comment by borgmanJeremy** [comment]
This should be fixed on the --edge channel. Will make it to stable tonight or tomorrow.

**Comment by notetiene** [comment]
I'm still encountering this issue.  I'm using version `11.0.0+git0.ad1bf28` from snap.

When save to any other than `/run/user/1000/doc/c43fe7d4/` (like home directory or even `/tmp`), it displays:
> Error trying to save as /run/user/1000/doc/c43fe7d4/test.png: No such file or directory
