### ISSUE TITLE
Screenshot is scaled down in Hi-DPI sway

### ISSUE THREAD

**Issue by refparo** [flameshot-org/flameshot#1705]
**Flameshot version**
`glameshot-git-r1369.6a54285f-1` from AUR

**Describe the bug**
Screenshot is scaled down in Hi-DPI under sway.

![图片](https://user-images.githubusercontent.com/13145126/125572202-bc33e9ae-a868-41df-8a22-e812a7490a0a.png)

**To Reproduce**

- Use an Hi-DPI configuration in sway, e.g. `output eDP-1 scale 1.25`
- Launch Flameshot and take a screenshot
(Remember to install `xdg-desktop-portal-wlr` and launch Flameshot with `XDG_CURRENT_DESKTOP=sway`)

**System Information**

Arch Linux

**Comment by nullobsi** [comment]
i implemented proper scaling support for the screenshot gui on sway/Wayland, but I only tested it with one 2x screen and one 1x screen

my guess is that the fractional scaling may confuse the devicePixelRatio and so Qt doesn't scale the image to fill the entire window
https://github.com/flameshot-org/flameshot/blob/2f087980729231b9d3c3d866e6b4a1cba1ec1f2f/src/utils/screengrabber.cpp#L108

**Comment by lunalicca** [comment]
It looks like this is still happening with current versions of Flameshot--with a scaling factor of 1.5 in Sway, the viewport shrinks as shown above when `flameshot gui` is triggered. Changing the scaling factor to a whole number restores the intended behavior. Are there any environmental variables that might be useful in working around this issue?

Using Fedora 37, Sway 1.7, Flameshot 12.1.0.

Thank you!

**Comment by sigprof** [comment]
I see the same problem on NixOS 22.11 (Flameshot v12.1.0, compiled with Qt 5.15.7; Sway 1.7) — after `swaymsg 'output * scale 2'` I get a full-sized screenshot in `flameshot gui`; however, after `swaymsg 'output * scale 1.75'` I see a scaled down screenshot.

Also it seems that the color picker still reads colors from the underlying full-screen image, and not from the resized image that is shown by `flameshot gui`.

**Comment by lunamode** [comment]
I did a little more testing on this issue with #3018—after compiling from source with `-DUSE_WAYLAND_GRIM=true`, it's actually possible to scale the preview window with environment variables. This command worked to get an *almost* accurately-scaled preview with a scaling factor of 1.5 in Sway:

`QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS="0.6667;1" flameshot gui`

Of course, this build comes with its own set of issues; the preview is much blurrier than the underlying desktop, ostensibly because it's being scaled multiple times, and making selections is extremely laggy. There's also a lot of visual artifacting that happens when the cursor is moved over a selection area. The saved screenshots look fine, though, just as they did with the prebuilt binary.

**Comment by ArcticLampyrid** [comment]
It looks like this issue still persists. I'm encountering it while using a scale factor of 1.5 under KDE (Wayland).

- Flameshot v12.1.0 (-)
- Compiled with Qt 5.15.16
