### ISSUE TITLE
Not Copying into Clipboard

### ISSUE THREAD

**Issue by Horuyuki** [flameshot-org/flameshot#1738]
Flameshot version: 0.10.0-1
OS: Arch with Gnome
Installed from AUR

Just captured a section like I always did, Ctrl+C to copy the image and paste to discord, nothing happens. Same result even if I manually click the copy button on the GUI.

Had been working before, could it be the newest version's problem?

Copied an image from discord directly and pasted it alright. So my clipboard is working as it should.

**Comment by mmahmoudian** [comment]
Any idea if you are on Wayland or not?

**Comment by thetaprimeprime** [comment]
After updated to the latest version, I can no longer copy directly to xfreerdp session. The old version has no such problem.
I have to first paste screenshot to GIMP, then copy from GIMP to xfreerdp session.

**Comment by thetaprimeprime** [comment]
I've tried running `xclip` to get clipboard information, **just after I copied a screenshot**, between the old and the latest version.

* v0.9.0
```
$ xclip -o -t TARGETS -selection clipboard
application/x-qt-image
image/png
image/bmp
image/cur
image/ico
image/jpeg
image/jpg
image/pbm
BITMAP
image/pgm
image/ppm
PIXMAP
image/xbm
image/xpm
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
```

* v0.10.0
```
$ xclip -o -t TARGETS -selection clipboard
image/png
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
```

It seems that v0.10.0 loses some information while copying images

**Comment by mmahmoudian** [comment]
@thetaprimeprime I tried the following and could not reproduce it.

![image](https://user-images.githubusercontent.com/390889/126618038-a340c2cf-5665-49d6-b938-698443449fd6.png)

Few thing to clarify and direct your attention to: 
- I added the `sleep 10s` to by myself enough time to let the `flameshot gui` opens, I select a region of the screen and press <kbd>Ctrl</kbd>+<kbd>c</kbd>.
- the first line of the output corresponds to the `flameshot --version`

**Comment by mmahmoudian** [comment]
@Horuyuki can you try to copy a screenshot with Flameshot and then instead of Discord, you paste it in something like Krita or Gimp?

Also please do as @thetaprimeprime suggested:
1. open a terminal
2. copy the `xclip -o -t TARGETS -selection clipboard` and paste it to the terminal
3. open flameshot and press copy (or <kbd>Ctrl</kbd>+<kbd>c</kbd>)
4. go to the terminal and run the command that you copied to step 2
5. copy-paste the output in this thread

**Comment by thetaprimeprime** [comment]
> @thetaprimeprime I tried the following and could not reproduce it.
> 
> ![image](https://user-images.githubusercontent.com/390889/126618038-a340c2cf-5665-49d6-b938-698443449fd6.png)
> 
> Few thing to clarify and direct your attention to:
> 
>     * I added the `sleep 10s` to by myself enough time to let the `flameshot gui` opens, I select a region of the screen and press Ctrl+c.
> 
>     * the first line of the output corresponds to the `flameshot --version`

The output for me is:
```
$ flameshot --version; flameshot gui; sleep 5s; xclip -o -t TARGETS -selection clipboard
Flameshot v0.10.0
Compiled with Qt 5.15.2
image/png
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
```

**Comment by mmahmoudian** [comment]
A difference I see is that my output has `x-qt-image`. I don't know what is the equivalent of that in Wayland. I will also add the Wayland label then.

**Comment by thetaprimeprime** [comment]
> A difference I see is that my output has `x-qt-image`. I don't know what is the equivalent of that in Wayland. I will also add the Wayland label then.

It seems to be also `x-qt-image` on wayland.

I'll try other versions such as flatpak or build directly from source, and see the results, when I have spare time.

**Comment by Horuyuki** [comment]
Alriu

> @Horuyuki can you try to copy a screenshot with Flameshot and then instead of Discord, you paste it in something like Krita or Gimp?
> 
> Also please do as @thetaprimeprime suggested:
> 
>     1. open a terminal
> 
>     2. copy the `xclip -o -t TARGETS -selection clipboard` and paste it to the terminal
> 
>     3. open flameshot and press copy (or Ctrl+c)
> 
>     4. go to the terminal and run the command that you copied to step 2
> 
>     5. copy-paste the output in this thread

Alright. For me it copied into GIMP perfectly fine. 

Output:
```
$ xclip -o -t TARGETS -selection clipboard
image/jpeg
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
```

**Comment by thetaprimeprime** [comment]
I found some clue.

https://github.com/flameshot-org/flameshot/blob/fbada715afcc61a245fbb56d01d294def19602d3/src/utils/screenshotsaver.cpp#L74

```cpp
        if (DesktopInfo().waylandDectected()) {
            saveToClipboardMime(capture, "png");
        } else {
            QApplication::clipboard()->setPixmap(capture);
        }
```

After I altered to these and recompile:

```cpp
        if (DesktopInfo().waylandDectected() && false) {
            saveToClipboardMime(capture, "png");
        } else {
            QApplication::clipboard()->setPixmap(capture);
        }
```

The problem solved (at least for me).

My system is on Wayland anyway.

Due to some reason, I cannot do more test and send a PR, sorry.

**Comment by mmahmoudian** [comment]
@thetaprimeprime I'm not a C++ developer, but my logic says that the `&& false` part you added always forces the `if` condition to always become `false` as the `&&` needs both sides to be `true` to make the whole condition to be `true`.

**Comment by thetaprimeprime** [comment]
> @thetaprimeprime I'm not a C++ developer, but my logic says that the `&& false` part you added always forces the `if` condition to always become `false` as the `&&` needs both sides to be `true` to make the whole condition to be `true`.

Yes. I added `&& false` to disable wayland check.

**Comment by mmahmoudian** [comment]
> Yes. I added `&& false` to disable wayland check.

and now you get output similar to [mine](https://github.com/flameshot-org/flameshot/issues/1738#issuecomment-884778610)?

**Comment by thetaprimeprime** [comment]
> > Yes. I added `&& false` to disable wayland check.
> 
> and now you get output similar to [mine](https://github.com/flameshot-org/flameshot/issues/1738#issuecomment-884778610)?

Not very similar, but there are BMP-some, and I'm capable to paste to other programs.

**Comment by Horuyuki** [comment]
So I suppose it will be fixed in the next release?

**Comment by mmahmoudian** [comment]
@borgmanJeremy Do you know if this is our bug or some QT issue in Wayland, and if there can be a hot fix for this in the next immediate release?

**Comment by thetaprimeprime** [comment]
> @borgmanJeremy Do you know if this is our bug or some QT issue in Wayland, and if there can be a hot fix for this in the next immediate release?

I will post a PR in one or two days.

**Comment by floatingrain** [comment]
This problem still stay in the latest version of flameshot, why don't you fix it? @mmahmoudian I'm using Gnome 3.38 on Wayland, every time I click the clipboard button after screenshot, it never works.

**Comment by borgmanJeremy** [comment]
@mmahmoudian we added this change to fix another wayland issue: https://github.com/flameshot-org/flameshot/issues/1568

**Comment by mmahmoudian** [comment]
@borgmanJeremy I'm a but confused (perhaps lack of sleep has also played its part), but is this already resolved by #1750?

**Comment by borgmanJeremy** [comment]
The author closed the pr after feedback so I'll need to fix it and merge it myself.

**Comment by Horuyuki** [comment]
So I was on the latest AUR release and I still cannot copy into places like discord while other things like GIMP worked.

**Comment by balazsorban44** [comment]
Having the same issues, even when I am not on Wayland:
![](https://i.imgur.com/3kgNVpr.png)
![](https://i.imgur.com/IIMJ8Ij.png)

**Comment by mmahmoudian** [comment]
I can confirm that with "Flameshot v0.10.1 (b2ecb70e)" still the issue exists on Xorg and I cannot paste the jpg even to this github thread.

<details>
<summary>The "Use JPG format for clipboard" is OFF</summary>

> ```
> ❯  xclip -o -t TARGETS -selection clipboard
> application/x-qt-image
> image/png
> image/avif
> image/bmp
> image/bw
> image/cur
> image/eps
> image/epsf
> image/epsi
> image/heic
> image/heif
> image/icns
> image/ico
> image/jp2
> image/jpeg
> image/jpg
> image/pbm
> BITMAP
> image/pcx
> image/pgm
> image/pic
> image/ppm
> PIXMAP
> image/rgb
> image/rgba
> image/sgi
> image/tga
> image/tif
> image/tiff
> image/wbmp
> image/webp
> image/xbm
> image/xpm
> TARGETS
> MULTIPLE
> TIMESTAMP
> SAVE_TARGETS
> ```


</details>

<details>
<summary>The "Use JPG format for clipboard" is ON</summary>

> ```
> ❯  xclip -o -t TARGETS -selection clipboard
> image/jpeg
> TARGETS
> MULTIPLE
> TIMESTAMP
> SAVE_TARGETS
> ```

</details>

**Comment by gaduaxe** [comment]
I got the same issue...

**Comment by Kaperios** [comment]
I'm encountering a similar problem, although I'm not 100% sure it's the same one. I found out that if the screenshot is small enough, you can paste it without any problems. The problem is when the file size gets too big. If they're too big you can't paste it to for example Discord and pasting it into GIMP shows that the screenshot is clearly corrupt.

Output of `flameshot --version`:
```
Flameshot v0.10.1 (d1428889)
Compiled with Qt 5.15.2
```
Arch with sway, 
Installed via the flameshot-git AUR package

**Comment by CMCDragonkai** [comment]
I'm running on NixOS, I upgraded from 21.11 to 22.05, and the `flameshot gui` clipboard copy no longer works. I click the copy button, and nothing is changed on my clipboard when I paste. I can copy paste images no problem.

Here's the output of my `xclip`:

```
»» ~
 ♜ xclip -o -t TARGETS -selection clipboard            pts/2 14:39:58
TIMESTAMP
TARGETS
SAVE_TARGETS
MULTIPLE
STRING
TEXT
UTF8_STRING
text/html
text/plain
text/plain;charset=utf-8
```

Something changed recently with flameshot or nixos packages that caused flameshot's copying to stop working. I'm still on X, and I use XMonad.

**Comment by Horuyuki** [comment]
It seems like you must use png.

**Comment by CMCDragonkai** [comment]
@Horuyuki what do you mean it must use png?

**Comment by Horuyuki** [comment]
> @Horuyuki what do you mean it must use png?

Closing the issue since it has been working fine for me. In KDE and Gnome settings, I had to set the screen captures to be in png format for them to be usable in the clipboard is all.

**Comment by CMCDragonkai** [comment]
Is that a new version of flameshot?

**Comment by mmahmoudian** [comment]
@CMCDragonkai 
> Is that a new version of flameshot?

https://github.com/flameshot-org/flameshot/releases/latest
