### ISSUE TITLE
Flathub flatpak flameshot version is still 0.10.1 when a flatpak release of 0.10.2 has occurred

### ISSUE THREAD

**Issue by ryannathans** [flameshot-org/flameshot#2090]
### Flameshot Version

0.10.1

### Installation Type

Flatpak from Flathub

### Operating System type and version

PopOS 20.04

### Description

Flathub flatpak flameshot version is still 0.10.1 when a flatpak release of 0.10.2 has occurred

### Screenshots or screen recordings

~$ flatpak update
Looking for updates…
Nothing to do.

flatpak list

Flameshot                                           org.flameshot.Flameshot                                           0.10.1                             stable                  user

### System Information

![image](https://user-images.githubusercontent.com/1307375/142547034-f50fb481-c21c-4ab7-b185-94bbcd3183fd.png)

**Comment by mmahmoudian** [comment]
@ryannathans the v0.10.2 is specifically released for Gnome 41 Wayland users. It doesn't have any new features or additional bug fixes. We are planning to release v0.11.0.

Also, the neofetch does not provide all the information we need. For instance it does not tell if you are using Wayland or X11. Please consider following [our guidelines for bug reporting](https://flameshot.org/guide/issue-reporting/) or use `inxi --system --graphics`

**Comment by mmahmoudian** [comment]
@borgmanJeremy we have also been asked on Mastodon that the v0.10.2 is not available on flathub. Would you please also put it on flathub. It would also solve this issue.

**Comment by ryannathans** [comment]
@mmahmoudian I didn't realise you needed more in-depth system specifications for a package not being published, I am not using wayland - I just get annoyed by the update popup every time I take a screenshot 

I will run `inxi --system --graphics` next time I'm at my pc

**Comment by mmahmoudian** [comment]
@ryannathans for this particular issue we don't need any information about your system as it is particularly about flathub. What I wrote was a general reminder as it is unfortunately common that we get neofetch/screenfetch/pfetch screenshots and then we have to ask again.

Anyways, thanks for your response 👍🏼. As far as I have tried, if you click on "ignore" button, it should not ask you about that new version anymore. But considering that we have published all binaries and packages for this release, it would be perhaps easy to also put this release on flathub. Thanks for opening the issue.

**Comment by borgmanJeremy** [comment]
I did publish it on flathub already. I wonder if the pipeline built it with an old version number by mistake.

**Comment by ryannathans** [comment]
I noticed there was an update in the last few days that I downloaded and installed but I did not see the version number increment

**Comment by borgmanJeremy** [comment]
Here is the root cause, our build pipeline for flatpak pulls from the master branch. This is because for every other release its been based on the master branch. 

However, in this case we released 10.2 as a hotfix on a maintenance branch. 

We need to change [this line](https://github.com/flameshot-org/flameshot/blob/53cc11ac58d87b75b2fd94d68a08ecd690a18ed2/.github/workflows/Linux-pack.yml#L592) on the **maintenance branch** and then re trigger the flatpak release.

I'll fix it by the end of the weekend.

**Comment by SebTM** [comment]
I was also a bit confused as the package in NixOS/Nixpkgs is up2date but Flameshot still show's me an update message each time I open it :D Thanks for taking care ✌🏻

**Comment by borgmanJeremy** [comment]
Will not fix, version 11 is coming out shortly.
