### ISSUE TITLE
Default algin to right

### ISSUE THREAD

**Issue by DarkCloudCZ** [flameshot-org/flameshot#2476]
Default align is set to right, even if I change it. When I take a screenshot and type some text, then I change the align to left, in the next screenshot it's in right again :(

**Comment by borgmanJeremy** [comment]
This should be fixed on the main branch #2448

**Comment by DarkCloudCZ** [comment]
Where can I get it? If I download this [Flameshot-11.0.0-win64.msi] on https://github.com/flameshot-org/flameshot/releases/tag/v11.0.0
It's still happening.

**Comment by mmahmoudian** [comment]
@DarkCloudCZ the easiest way to get the development builds is via:

https://flameshot.org/docs/installation/development-build/

**Comment by DarkCloudCZ** [comment]
Thank you.
