### ISSUE TITLE
flameshot "open with" window is blank

### ISSUE THREAD

**Issue by artichoked1** [flameshot-org/flameshot#3046]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3

### Installation Type

Snap from Snapcraft

### Operating System type and version

Linux, Ubuntu 22.10

### Description

The window that opens up when you click "open with Other application" has no icons, text or applications in it. see following screenshot:
![Screenshot from 2023-01-07 10-08-05](https://user-images.githubusercontent.com/41409702/211117558-41d6f3a7-e78d-4ef5-955a-616a1bcf17ef.png)

When I run click the button, the following message shows up in the terminal output:
`/usr/share/libdrm/amdgpu.ids: No such file or directory`

### Steps to reproduce

1. Start flameshot (`flameshot gui`)
2. Make a selection
3. Click the "choose an application to open capture"button or use the default keybind `ctrl+o`
4. Observe the broken selection window

### System Information

OS: Ubuntu 22.10
Kernel: 5.19.0-26-generic
Hardware: AMD Ryzen 5 5600X, 16 GB DDR4 RAM, AMD Radeon™ RX 6600, 500GB SSD
Desktop enviroment:  GNOME 43.1
Windowing system: Xorg

inxi output:
```
System:
  Host: UberFastPC-ubuntu Kernel: 5.19.0-26-generic arch: x86_64 bits: 64
    Desktop: GNOME v: 43.1 Distro: Ubuntu 22.10 (Kinetic Kudu)
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu
    v: kernel
  Display: x11 server: X.Org v: 1.21.1.4 with: Xwayland v: 22.1.3 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
    resolution: 1680x1050~60Hz
  OpenGL: renderer: AMD Radeon RX 6600 (navi23 LLVM 15.0.2 DRM 3.47
    5.19.0-26-generic) v: 4.6 Mesa 22.2.1
```

**Comment by thomassvensen** [comment]
I have the exact same issue, same Flameshot version, running on Windows 11.

**Comment by thinrope** [comment]
Can someone shed more info on what is supposed to shoe there and where does it take this information from?
On my system (Gentoo Linux) it shows a lot of apps, though the Tabs seem somewhat broken and without title...
![image](https://github.com/flameshot-org/flameshot/assets/754020/63d392ed-6e41-4ae6-9b4e-d56c32b5338a)

Funny enough I couldn't use flameshot to take a screenshot of its own dialog :-)

**Comment by brad-charboneau** [comment]
I to have the same Issue as OP and @thomassvensen on Windows 11 Pro 23H2 Build 22631

App chooser is blank.

**Comment by mmahmoudian** [comment]
The #3663 was merged. And it should fix this issue. I will close this for now, but if this persists in the next Snap version, please let us know to re-open this.

**Comment by antontsvil** [comment]
@mmahmoudian I have the latest version (12.1.0) installed via flatpak on an Ubuntu 20.04 and am still experiencing this issue

![Image](https://github.com/user-attachments/assets/89ab1333-274a-4d55-a3ce-65aa730018ac)
