### ISSUE TITLE
Forward slashes used in save path on windows

### ISSUE THREAD

**Issue by dt192** [flameshot-org/flameshot#3135]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

winnt: 10.0.19045 windows: 10

### Description

When using 'copy file path after save' on windows, the path is copied with forward slashes which when pasted into a windows file open dialogue just throws an error. These need replacing with backslashes on windows to make this feature useful.

### Steps to reproduce

1. Install Flameshot on windows
2. Enable 'Copy file path after save'
3. Save a screenshot
4. Paste path into a file open dialogue (Discord/Photoshop for example)
5. Click open

### Screenshots or screen recordings

![2023-03-17_15-59](https://user-images.githubusercontent.com/2612048/226109034-774e1663-13ed-4e9e-9b92-b31b4df3b7ae.png)

### System Information

winnt: 10.0.19045
windows: 10

**Comment by subsense33** [comment]
I can confirm this bug (Win11 23H2)

**Comment by subsense33** [comment]
@dandv How can I "confirm" this bug?
I have the same issue as @dt192

**Comment by borgmanJeremy** [comment]
Fixed with #3136

**Comment by mmahmoudian** [comment]
@dt192 @subsense33 Just to be clear, this will be available in the next release (version 13)

**Comment by dt192** [comment]
Still not rolled out this fix from 2 years ago? Wouldn't it be better to release bug fixes more often.

**Comment by ElTh0r0** [comment]
I fear I reverted these changes with #4027 / #3997 while fixing other Windows file path related issues...
I'll take a look on that during the next days hoping, that I have a full picture of all places now where the file path could cause issues...

**Comment by dt192** [comment]
Still not fixed then. Maybe this should be reopened.

**Comment by ElTh0r0** [comment]
@dt192 which version are you using? Above mentioned PR #4122 was included in v13.1; but better switch directly to v14.0

**Comment by dt192** [comment]
@ElTh0r0 It was v14, however I hadn't realised it didn't have the copy path to clipboard option turned on and I just happened to still have a path on the clipboard from the previous version. I have retested and can confirm this is fixed. Many thanks.
`D:\user\media\pics\2026-06-29_16-29_1.png`
