### ISSUE TITLE
Default save path not respected, defaults to ~/Picutres

### ISSUE THREAD

**Issue by TheToddLuci0** [flameshot-org/flameshot#3795]
### Flameshot Version

```
Flameshot v12.1.0 (Debian 12.1.0+ds-1)
Compiled with Qt 5.15.13
linux: 6.11.2-amd64
kali: 2024.4
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux kali 6.11.2-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15) x86_64 GNU/Linux

### Description

When taking consecutive screenshots, flameshot does not respect the default save path, and instead instead saves it in `~/Pictures`.

### Steps to reproduce

- Take a screenshot, and save it in `/some/place`
- Default save path is automatically set to `/some/place`
- Take a second screenshot
  - At this point, the save dialogue opens to `~/Pictures`, rather than `/some/place`

### System Information

```
$ inxi --width 80 --system --graphics
System:
  Host: kali Kernel: 6.11.2-amd64 arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: Kali GNU/Linux 2024.4 kali-rolling
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.20.0.0
  Display: x11 server: X.Org v: 21.1.13 driver: X: loaded: vmware
    unloaded: fbdev,modesetting,vesa dri: vmwgfx gpu: vmwgfx
    resolution: 2560x1600~60Hz
  API: EGL v: 1.4,1.5 drivers: swrast,vmwgfx
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.5 compat-v: 4.3 vendor: vmware mesa v: 24.2.7-1
    renderer: SVGA3D; build: RELEASE; LLVM;
```

**Comment by Cboughton** [comment]
Same issue on XUbuntu24.04d. Path set explicitly is randomly updated to a new path that does not exist in the device.

**Comment by mmahmoudian** [comment]
@TheToddLuci0 can you also share your|`flameshot.ini` config file. It should be in `~/.config/flameshot/`.

**Comment by TheToddLuci0** [comment]
@mmahmoudian 
```ini
[General]
contrastOpacity=188
drawColor=#ff1600
saveAsFileExtension=png
savePath=/home/kali/client/CLIENT_NAME/evidence
showStartupLaunchMessage=false
startupLaunch=true
```

**Comment by borgmanJeremy** [comment]
Could you test with the v13 beta we just published? I couldn't replicate this before and I wonder if its fixed on the new version.

**Comment by TheToddLuci0** [comment]
The issue still persists with the [v13.0.rc2](https://github.com/flameshot-org/flameshot/releases/tag/v13.0.rc2) release. 

Since opening the issue, I've actually switched from Kali linux to NixOS. The one thing that's stayed the same is that the location I'm trying to save to is a symlink to a mounted VMWare hgfs share. The issue does not persist when saving to a "normal" location (ie /tmp/)

<img width="940" height="121" alt="Image" src="https://github.com/user-attachments/assets/a4f069a9-7523-49ec-bd46-22b91da8e96f" />

```
Flameshot v13.0.0 ()
Compiled with Qt 6.9.0
linux: 6.12.36
nixos: 25.11
```

**Comment by TheToddLuci0** [comment]
Poking around in gdb, the issue seems to be here:
 https://github.com/flameshot-org/flameshot/blob/39ce5d16af48d6a5f1d15027fada04e245d68124/src/utils/screenshotsaver.cpp#L226

<img width="983" height="317" alt="Image" src="https://github.com/user-attachments/assets/0986d3e9-0430-4145-b1f7-4689ca8a5fbd" />

It appears that for some reason,  `isWritable` is returning false, even though I can save screenshots there no problem. c++ isn't a language I'm super familiar with, so I double checked with the classic "put a print statement there", and we can see that the string is not empty, the filepath exists, but it thinks it's not writable.

<img width="909" height="459" alt="Image" src="https://github.com/user-attachments/assets/a9ad1c46-9766-4a98-86bf-ccd8d66c5300" />
