### ISSUE TITLE
Left monitor becomes right monitor and right monitor becomes blank

### ISSUE THREAD

**Issue by zperk13** [flameshot-org/flameshot#4128]
### Flameshot Version

I'm on flameshot v13.0.1. This issue also existed in flameshot 13.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

EndeavourOS

### Description

I have two monitors. If I run `flameshot gui`, my left monitor looks like my right monitor and my right monitor goes black. and I get this output
```
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawEllipse: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawEllipse: Painter not active
```

If I run `flameshot launcher`, my monitors remain fine, but in the preview window on the launcher, it thinks my right monitor is the left monitor, and my right monitor is black. Basically recreating what I see with `flameshot gui`. There is no output to the command line.

If I downgrade to flameshot v.12.1.0 (compiled with Qt 5.15.16 instead of 6.9.1), I don't have the issue.

### Screenshots or screen recordings

<img width="3839" height="1079" alt="Image" src="https://github.com/user-attachments/assets/50eeceee-60ca-4968-ad76-af5993377310" />

<img width="488" height="243" alt="Image" src="https://github.com/user-attachments/assets/dbd33cf9-2fc2-4d53-a0ec-d25ad26bd0f1" />

### System Information

Flameshot v13.0.1 ()
Compiled with Qt 6.9.1

```
~ $ inxi --width 80 --system --graphics
System:
  Host: z-pc Kernel: 6.15.9-arch1-1 arch: x86_64 bits: 64
  Desktop: i3 v: 4.24 Distro: EndeavourOS
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900
    XTX/7900 GRE/7900M] driver: amdgpu v: kernel
  Device-2: Advanced Micro Devices [AMD/ATI] Raphael driver: amdgpu v: kernel
  Device-3: Logitech C920 PRO HD Webcam driver: snd-usb-audio,uvcvideo
    type: USB
  Display: x11 server: X.Org v: 21.1.18 driver: X: loaded: amdgpu
    unloaded: modesetting,radeon dri: radeonsi gpu: amdgpu resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 25.1.7-arch1.1
    renderer: AMD Radeon RX 7900 XTX (radeonsi navi31 LLVM 20.1.8 DRM 3.63
    6.15.9-arch1-1)
  Info: Tools: api: clinfo, eglinfo, glxinfo x11: xdpyinfo, xprop, xrandr
```

```
~ $ loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
x11
```

```
~ $ xrandr --listactivemonitors
Monitors: 2
 0: +DisplayPort-1 1920/531x1080/299+1920+0  DisplayPort-1
 1: +HDMI-A-1 1920/531x1080/299+0+0  HDMI-A-1
```

```
~ $ xrandr | grep -v " disconnected "
Screen 0: minimum 320 x 200, current 3840 x 1080, maximum 16384 x 16384
DisplayPort-1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     60.00*+  50.00    59.94  
   1680x1050     59.88  
   1280x1024     60.02  
   1440x900      59.90  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      70.07    60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       66.67    60.00    59.94  
   720x400       70.08  
HDMI-A-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     60.00*+  50.00    59.94  
   1680x1050     59.88  
   1280x1024     60.02  
   1440x900      59.90  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      70.07    60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       66.67    60.00    59.94  
   720x400       70.08  
```

```
~ $ lspci | grep -i 'vga\|3d\|2d'
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900 GRE/7900M] (rev c8)
47:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raphael (rev c1)
```

```
~ $ uname -a
Linux z-pc 6.15.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 02 Aug 2025 01:20:06 +0000 x86_64 GNU/Linux
```

<details>
<summary>The dbus-monitor content</summary>

```

signal time=1754546363.850270 sender=org.freedesktop.DBus -> destination=:1.630 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.630"
signal time=1754546363.850280 sender=org.freedesktop.DBus -> destination=:1.630 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.630"
method call time=1754546368.201216 sender=:1.631 -> destination=org.freedesktop.DBus serial=8 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus'"
method call time=1754546368.201226 sender=:1.631 -> destination=org.freedesktop.DBus serial=9 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.a11y.Bus"
method call time=1754546368.201355 sender=:1.631 -> destination=org.freedesktop.DBus serial=10 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.a11y.Bus"
method call time=1754546368.201383 sender=:1.631 -> destination=org.freedesktop.DBus serial=11 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus',arg1=''"
method call time=1754546368.201404 sender=:1.631 -> destination=org.freedesktop.DBus serial=12 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameHasOwner
   string "org.a11y.Bus"
method call time=1754546368.201457 sender=:1.631 -> destination=org.a11y.Bus serial=13 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "ScreenReaderEnabled"
method call time=1754546368.201676 sender=:1.631 -> destination=org.a11y.Bus serial=14 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "IsEnabled"
method call time=1754546368.201820 sender=:1.631 -> destination=org.freedesktop.DBus serial=15 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.a11y.Bus',path='/org/a11y/bus',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'"
method call time=1754546368.201828 sender=:1.631 -> destination=org.freedesktop.DBus serial=16 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus'"
method call time=1754546368.201832 sender=:1.631 -> destination=org.freedesktop.DBus serial=17 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.a11y.Bus"


```

</details>

**Comment by Haaduken** [comment]
I am also encountering this issue with the latest build, reproduced it on 13.0.1 and am seeing identical behaviour 
```
inxi --width 80 --system --graphics
System:
  Host: arch Kernel: 6.12.41-1-lts arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.4.4 Distro: Arch Linux
Graphics:
  Device-1: NVIDIA AD103 [GeForce RTX 4080] driver: nvidia v: 575.64.05
  Device-2: Logitech HD Pro Webcam C920 driver: snd-usb-audio,uvcvideo
    type: USB
  Display: x11 server: X.Org v: 21.1.18 with: Xwayland v: 24.1.8 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: N/A 2: N/A
  API: EGL v: 1.5 drivers: nvidia,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 575.64.05
    renderer: NVIDIA GeForce RTX 4080/PCIe/SSE2
  API: Vulkan Message: No Vulkan data available.
  Info: Tools: api: clinfo, eglinfo, glxinfo, vulkaninfo
    de: kscreen-console,kscreen-doctor gpu: nvidia-settings,nvidia-smi
    wl: wayland-info x11: xdriinfo, xdpyinfo, xprop, xrandr
```
```
xrandr --listactivemonitors
Monitors: 2
 0: +*DP-2 2560/597x1440/336+2560+0  DP-2
 1: +DP-4 2560/597x1440/336+0+0  DP-4
```

**Comment by z1atk0** [comment]
Same here, built from source on Slackware64-15.0. Output from _About => Copy Info_:
```
Flameshot v13.0.1 ()
Compiled with Qt 6.9.1
linux: 6.12.41
slackware: 15.0
```
Additional info:
```
[zlatko@disclosure:~]$ inxi --width 80 --system --graphics
System:
  Host: disclosure.zlatk0.net Kernel: 6.12.41 arch: x86_64 bits: 64
  Desktop: GNOME v: 47.7 Distro: Slackware 15.0
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1660 Ti] driver: nvidia v: 570.181
  Device-2: Sunplus Innovation Full HD webcam driver: snd-usb-audio,uvcvideo
    type: USB
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 21.1.4 driver: X:
    loaded: nvidia unloaded: nouveau gpu: nvidia,nvidia-nvswitch resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: nouveau,nvidia,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 570.181
    renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
  API: Vulkan v: 1.4.313 drivers: nvidia,llvmpipe surfaces: N/A
  Info: Tools: api: eglinfo, glxinfo, vulkaninfo gpu: intel_gpu_top, lsgpu,
    nvidia-settings, nvidia-smi x11: xdriinfo, xdpyinfo, xprop, xrandr
```
```
[zlatko@disclosure:~]$ xrandr --listactivemonitors
Monitors: 2
 0: +*HDMI-1 1920/544x1080/303+1920+0  HDMI-1
 1: +HDMI-0 1920/544x1080/303+0+0  HDMI-0
```
```
[zlatko@disclosure:~]$ xrandr | grep -v " disconnected "
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
HDMI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 544mm x 303mm
   1920x1080     60.00*+ 240.00   165.00   119.98   119.88    59.94    50.00  
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
HDMI-1 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 544mm x 303mm
   1920x1080     60.00*+ 240.00   165.00   119.98   119.88    59.94    50.00  
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
```

**Comment by Bump-Action** [comment]
A similar problem on windows 11 24h2. The image of all monitors shifts to the left when taking a screenshot
Flameshot 13.0.0

**Comment by fiwjfwkfpwekfpo** [comment]
✅ I can confirm this issue is real, but it manifests a bit differently in my setup:

    Flameshot sometimes captures its own GUI when initiating flameshot gui. Other times it works correctly—but only on the primary monitor.

    On the second monitor, things go wrong:

        Content from Monitor 1 gets projected—or even overlaid—onto Monitor 2,

        This overlay sometimes appears partially (in fragments),

        Because I use window transparency, I can clearly see Monitor 1 visuals misplaced on Monitor 2, layered on top of everything else.

📌 Important note: This issue did not happen in previous versions — everything worked fine before the recent updates.

This behavior differs from the left/right swap described here but is clearly related to multi‑monitor rendering glitches in the latest Flameshot version. Hope it helps diagnose the issue. Let me know if you need logs, screenshots or commands to reproduce.

**Comment by Maxcrazy1** [comment]
I had the same issue, this issue began after one of the most recent updates.

**Comment by pienapin** [comment]
its already reported here #4111 and someone already did a pull request to fix it #4127, so wait for next update i guess

**Comment by z1atk0** [comment]
> its already reported here https://github.com/flameshot-org/flameshot/issues/4111 and someone already did a pull request to fix it https://github.com/flameshot-org/flameshot/pull/4127, so wait for next update i guess

Yup, that pull request seems to fix the problem for me. Thanks! 🙂

**Comment by MKastuv** [comment]
Same issues as this one with three monitors. Monitor #3 shows as monitor #1 in flameshot and then monitor #2 and #3 shows blank now. Right after upgrade to 13.

**Comment by ionsquare** [comment]
@MKastuv that's the same setup I have with 3 monitors and the same problem I experienced, #4127 fixes it.

**Comment by MKastuv** [comment]
@ionsquare  how did you install 13.0.1? "sudo pacman -S flameshot" still has tagged to 13.0.0

**Comment by ionsquare** [comment]
@MKastuv yes, just `pacman -Syu flameshot`

```sh
╰─❯ pacman -Q flameshot
flameshot 13.0.1-1
```

**Comment by MKastuv** [comment]
Thanks, I updated it to latest but sadly issue persists :(

**Comment by ionsquare** [comment]
Fix isn't merged yet, waiting for approval.

**Comment by MKastuv** [comment]
Thanks for your help. Hope we will get the approval soon. Great software and crippled without it as my keybindings are depending on it.

**Comment by Swivelgames** [comment]
> [!NOTE]
> For those on **Arch Linux _btw_** looking to resolve this temporarily, you should be able to downgrade with something _like_ this:
> 
> ```
> sudo pacman -U /var/cache/pacman/pkg/flameshot-12.1.0-6-x86_64.pkg.tar.zst
> ```
>
> Obviously, choose the version of flameshot you previously had installed, but if you've been keeping your machine up to date, it should be some variation of flameshot-12.1.0-**X**.
>
> @MKastuv also suggested adding the following to your `/etc/pacman.conf`:
> ```
> IgnorePkg = flameshot
> ```
> **_Be sure to subscribe to this issue, and/or #4111, so that you remember to remove this later when you get notified that these issues are closed._** 👍 

This is happening to me as well.

Here's what I get when I use `flameshot gui` and drag to select the whole screen:

<img width="3640" height="1919" alt="Image" src="https://github.com/user-attachments/assets/6584c688-d65f-4d0c-aaad-596b776c8954" />

Here's what I get when I use `shotgun` to capture the whole screen:

<img width="3640" height="1920" alt="Image" src="https://github.com/user-attachments/assets/c29f6279-ef2d-4361-9a64-7cd1a1f4a51d" />

**Comment by masymularif** [comment]
Having the same issue here. Reverted to version 12.1 for now :)

**Comment by MKastuv** [comment]
Good idea, not sure when another version is coming out. Also added "IgnorePkg = flameshot" in /etc/pacman.conf after downgraded.

**Comment by ChimeraGaming** [comment]
Which one is the main ticket? 
I've come across  4 now that are closed but it's not closed as it's still persistent in 13.0.1 and there is no further updates at this time.
Confirmed Bug still persistent on Both win10 and win11

@borgmanJeremy

**Comment by Swivelgames** [comment]
@ChimeraGaming Should be:

- #4111

I believe this was just fixed in:

- #4127

**Comment by ChimeraGaming** [comment]
> [@ChimeraGaming](https://github.com/ChimeraGaming) Should be:
> 
> * [V13 bug, screen offset on dual monitor #4111](https://github.com/flameshot-org/flameshot/issues/4111)
> 
> I believe this was just fixed in:
> 
> * [Fix multi monitor offset bug in Qt6 multi-monitor setups for X11 #4127](https://github.com/flameshot-org/flameshot/pull/4127)

Cool looks like it was fixed 3 days ago in v13.1.0
Trying it now, no news is good news.

EDIT: Yeah it's broken worse now...

**Comment by Tobleh** [comment]
I can confirm that the issue is still happening for me as well - using flameshot-13.1.0-1 from the Arch repos on GNOME 48.4 using Wayland.

**Comment by GuelBandeira** [comment]
I have the same issue in Windows, using the version 13.3.0

**Comment by ChimeraGaming** [comment]
Yeah it wasn’t really fixed. They just closed it 😂 

We told them the issue is with 
- Multiple Screens 
- when NOT at 100% resolution 
It legit was never resolved….

**Comment by mmahmoudian** [comment]
@ChimeraGaming 
> Yeah it wasn’t really fixed. They just closed it 😂 
> 
> We told them the issue is with 
> - Multiple Screens 
> - when NOT at 100% resolution 
> It legit was never resolved….


False. This is fixed with #4498. Paying attention to PRs sometimes matter.

@GuelBandeira
Please checkout the links I provided in #4579 for windows:
https://github.com/flameshot-org/flameshot/issues/4579#issuecomment-4090671814

**Comment by ChimeraGaming** [comment]
> @ChimeraGaming 
> > Yeah it wasn’t really fixed. They just closed it 😂 
> > 
> > We told them the issue is with 
> > - Multiple Screens 
> > - when NOT at 100% resolution 
> > It legit was never resolved….
> 
> 
> False. This is fixed with #4498. Paying attention to PRs sometimes matter.

If it was fixed we wouldn't be on the latest update still have the same issue from months ago. It also helps to pay attention to the mass 

I raised the concern as soon as they said it was "fixed" if you look above 

![image](https://github.com/user-attachments/assets/72307e05-1fd7-4ad2-a2b8-41f4197ef842)

**Comment by mmahmoudian** [comment]
@ChimeraGaming 
> If it was fixed we wouldn't be on the latest update still have the same issue from months ago. It also helps to pay attention to the mass
> 
> I raised the concern as soon as they said it was "fixed" if you look above

Let's be clear about few important points:
1. This was merged about few weeks ago, not months ago! It have been confirmed by everyone who have used it that this solved the issue. So try it before accusing!

2. This is a community project. The devs do not owe anyone anything. Purely volunteer work. Similar to the devs that are trying their best to improve the project, you can also step up and give a hand and make a difference.

**Comment by zperk13** [comment]
I'm the one who originally opened this issue. The issue was fixed months ago, I haven't had problems in a while.

**Comment by ChimeraGaming** [comment]
> @ChimeraGaming 
> > If it was fixed we wouldn't be on the latest update still have the same issue from months ago. It also helps to pay attention to the mass
> > 
> > I raised the concern as soon as they said it was "fixed" if you look above
> 
> Let's be clear about few important points:
> 1. This was merged about few weeks ago, not months ago! It have been confirmed by everyone who have used it that this solved the issue. So try it before accusing!
> 
> 2. This is a community project. The devs do not owe anyone anything. Purely volunteer work. Similar to the devs that are trying their best to improve the project, you can also step up and give a hand and make a difference.

PR is only "help"
It's not releases. Until the release is update it's still "broken" 

I can't add PR to my work computer 
![image](https://github.com/user-attachments/assets/9b5b8280-6e3a-4e48-a3cc-ce38d2a3cfa4)

**Comment by ChimeraGaming** [comment]
> I'm the one who originally opened this issue. The issue was fixed months ago, I haven't had problems in a while.

That must be nice 😅 
Just out of curiosity how many screens you running and do you adjust resolution scale?

**Comment by zperk13** [comment]
>  Just out of curiosity how many screens you running

2

> do you adjust resolution scale?

no

**Comment by ChimeraGaming** [comment]
> >  Just out of curiosity how many screens you running
> 
> 2
> 
> > do you adjust resolution scale?
> 
> no

Yea the issue we all have is with multiple monitors and when resolution scale is adjusted. You were like 1 of 3 that didn't adjust scale. But 95% of this thread became issues with multiple screen and resolution scale

**Comment by mmahmoudian** [comment]
@ChimeraGaming 
> I can't add PR to my work computer

Ask your sysadmin. They hopefully know how to click on the link I shared and install it for you. 🤷

> the issue we all have is with multiple monitors and when resolution scale is adjusted. 

Monitors are handled separately now, so regardless of the number of monitors or their resolution or scale, Flameshot now works. This have been extensively tested on Windows and Linux.

**Comment by z1atk0** [comment]
> > [@ChimeraGaming](https://github.com/ChimeraGaming)
> [...]
> PR is only "help" It's not releases. Until the release is update it's still "broken"
> [...]

Well then, how about you just wait for an actual release if you already know that it has been fixed, instead of spamming a closed bug report again and again? Just a random idea. 🤷‍♂️ 

For the record: yes, I'm also one of the lucky ones for whom the bug has been fixed with the first PR #4127 already. I downloaded the PR as a set of diffs, patched the original source code with it, recompiled, done. If you can't or don't want to build for yourself, _just wait for a release_. Thank you! 🙏

**Comment by Swivelgames** [comment]
@ChimeraGaming I don't blame you. But they casually dropped a massive refactor that broke for tons of people, and now they're swimming in issues, and are too afraid of putting out an actual release again.

At least I have the luxury of pulling this down and building/running it locally, which doesn't work in your case.

The next release is never going to be perfect. They need to release these fixes incrementally. The more fixes they accumulate, the harder the next release is going to hit them.

It's been nearly 7 months. A month or two? Sure. But 7 months? If they wait until the next release is perfect, they're going to have the same problem when they dropped `13.3.0`. It's going to bomb and everyone's going to complain about new issues.

If they're too afraid of messing up the next release, people are eventually going to stop waiting and go to something else.

---

> @z1atk0 
> instead of spamming a closed bug report again and again? Just a random idea.

@z1atk0 To your point, this ticket is closed. You don't have to stay and continue to contribute to the conversation if you don't want to ❤️ If you're bothered by the notifications, you should be able to unsubscribe so they don't bother you anymore 👍 

<img width="311" height="142" alt="Image" src="https://github.com/user-attachments/assets/a628a89f-797a-431f-98c0-61be5946e9b0" />

**Comment by borgmanJeremy** [comment]
I'm not afraid of a release, I'm incredibly busy and managing this in my free time. The fix is already available on our release page in beta form and I'm in the process of releasing a second beta.

**Comment by ChimeraGaming** [comment]
Beta is being blocked by my Work's Domain level security but the other version prior to was not.
