### ISSUE TITLE
Windows 11 getting with every update worst

### ISSUE THREAD

**Issue by erikpa1** [flameshot-org/flameshot#4296]
### Flameshot Version

Flameshot v13.1.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11

### Description

Hi I tried new version because of problem where secondary monitor is OK , but primary get both monitors on single screen, but with update even second monitor can't get proper printscreen... 

<img width="2048" height="1536" alt="Image" src="https://github.com/user-attachments/assets/14fdc80d-d775-416a-b0eb-3956f87a1342" />

My graphics card:

<img width="655" height="387" alt="Image" src="https://github.com/user-attachments/assets/ce588b2d-afb0-47e4-a10a-33ea3baec998" />

### Steps to reproduce

Press printcreen on this resolution and graphics card ??

### Screenshots or screen recordings

My monitors:

<img width="2050" height="866" alt="Image" src="https://github.com/user-attachments/assets/ead9c8e4-50f3-4346-892c-2addecd8de4b" />
1.
<img width="2135" height="876" alt="Image" src="https://github.com/user-attachments/assets/6c278c60-2bd1-48d3-8018-937805ab8e7d" />

2.

<img width="2092" height="813" alt="Image" src="https://github.com/user-attachments/assets/c92c1cb2-c630-497d-b270-f165825d190a" />

### System Information

1. Windows 11
2. Microsoft Surface Pro 8.

**Comment by borgmanJeremy** [comment]
Please search for duplicates first

**Comment by erikpa1** [comment]
@borgmanJeremy  Watchet threads before, only same feedback was from Arch Linux,... I report it from windwos 11 integrated card ...   and also for me even the primary monitor is not working..

**Comment by mmahmoudian** [comment]
@borgmanJeremy I wonder if this is partly or fully fixed with the PRs @panpuchkov made specifically #4230

**Comment by borgmanJeremy** [comment]
Could be, I've been hesitant to release that as we know it doesn't fully fix the issue and I thought it would spawn another round of duplicate issues.

As the permanent fix isn't ready I'll defer to you on if you want me to do another interim release for v13

**Comment by mmahmoudian** [comment]
@borgmanJeremy I agree with you that the changes we have had are partial fixes, but I think we can plan a minor release for what we have in the form of a pre-release. This means that Windows, Deb, and AppImage users will be able to give it a try. This way we get a better idea of how it works for a subset of users and their monitor setups. Later we can merge some more PRs have a stable release for v13.2.0 if things goes well. If not, we can keep it in pre-release mode until we are more confident about it.

As a side-note, I have been busy lately and haven't had time to read every single comment in all the issues, so I don't have a clear picture of how the current PRs are trying to solve the monitor and coordinate issues. My schedule gets more relaxed by Nov 10th and I can invest much more time on this and help with the release. That said, I'll spend some time this weekend on some of the things I've assigned to myself, and do some triage and cleanups.
