### ISSUE TITLE
On a Win11 3-monitors setup, the V13.3.0 shifts all desktops to the left

### ISSUE THREAD

**Issue by yphil05** [flameshot-org/flameshot#4433]
### Flameshot Version

Flameshot v13.3.0 (da913d7f)
Compiled with Qt 6.9.2
winnt: 10.0.26200
windows: 11

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Win11 (25H2, build 26200.7171)

### Description

Hi

My main screen is the middle monitor, quite naturally. When I click on FlameShot's icon to take a snapshot:
1. the middle desktop shifts to the left monitor
2. the right desktop shifts to the middle monitor
3. the right monitor becomes black
4. the left desktop has disappeared

Same effects happens with the launcher as soon as I validate after having selected the seconds to wait before taking a snapshot.

Thanks in advance.
Phyl

### Steps to reproduce

Either click on the Flameshot icon on the taskbar or use the launcher and select a few second, then validate

### System Information

Win11 installation (25H2, build 26200.7171)
3x 23"-monitors, the middle one being the main desktop
NVidia RTX 4070

**Comment by kawakode** [comment]
I have the exact same issue, latest version of Flameshot.

**Comment by Rice-Chris-P** [comment]
I have the same issue. It looks to be related to the multi-monitor display setup- when I change my 3 monitor display settings to 1-2-3 all is fine, but changing my monitors to the actual layout (2-1-3) breaks flameshot.

**Comment by mockpulsar** [comment]
Same issue here. 
Flameshot v13.3.0 (da913d7f)
Compiled with Qt 6.9.2
winnt: 10.0.26100
windows: 11

I have 2 monitors, main is at 2560x1440. Secondary is 1920x1080.
Issue is that the content of the Main, slides to my secondary, overlaps on the main, content of the secondary disappears.

**Comment by ChriWRZ** [comment]
Same issue, but with 2 monitors. It also affects around 30 other people at my company. For me, the bug appears in every release variant of version 13, but it does not occur in the latest version 12.1.0. 

- Occurs in every release variant of version 13 (but not in the latest version 12.1.0)
- OS: Windows 11 and MS Windows Server 2019 Datacenter
- Occurs at 100% scaling as well as at higher scaling levels, so at least in my case, it doesn’t seem to be related to the scaling
- Resolution: 2560x1440
- Monitor size: 27 inch

**Comment by Thundzz** [comment]
> Same issue, but with 2 monitors. It also affects around 30 other people at my company. For me, the bug appears in every release variant of version 13, but it does not occur in the latest version 12.1.0.
> 
> * Occurs in every release variant of version 13 (but not in the latest version 12.1.0)
> * OS: Windows 11 and MS Windows Server 2019 Datacenter
> * Occurs at 100% scaling as well as at higher scaling levels, so at least in my case, it doesn’t seem to be related to the scaling
> * Resolution: 2560x1440
> * Monitor size: 27 inch

@n0xay Thanks a lot for pointing out that the issue is specific to 13.x versions. I had the exact same problem and I had removed the program. When I saw your comment I rolled back to the last 12.x version (Flameshot v12.1.0 (96c2c82e)), and it indeed works properly 🙏

**Comment by ronenb75** [comment]
Same problem.
Tried `flameshot-13.3.0-win64.zip` on Windows 11 `Version	10.0.22631 Build 22631`.

Works perfect with `v12.1.0`

**Comment by StarsLikeDust** [comment]
I'm experiencing the same issue with Flameshot 13.3 on Windows 11 and multiple monitors though in my case how the image shifts depends on the layout of the displays in windows settings. With the following display arrangement Flameshot works as expected:

<img width="579" height="347" alt="Image" src="https://github.com/user-attachments/assets/903b17eb-68e4-49de-bda5-e629feca448f" />

If I update the display arrangement in settings to reflect the physical monitor layout Flameshot shifts the display image on both monitors vertically when activated. 

Layout that breaks Flameshot on my machine:

<img width="579" height="347" alt="Image" src="https://github.com/user-attachments/assets/a322132a-45ff-4260-8c12-0ed4c4321d7f" />

It feels like the vertical image offset Flameshot introduces matches the amount display two sticks up above display one.

**Comment by jeromba6** [comment]
I seem to have the same problem but it is resolved when changing the "Main display" to my monitor 1 wich is on the most left.

<img width="1855" height="1007" alt="Image" src="https://github.com/user-attachments/assets/6beaf9ad-bee6-4cdb-97fa-eb442cd7ea13" />

**Comment by thatrex** [comment]
I am on Windows 11 24H2 and have this same issue starting with `v13.2.0`. Like @jeromba6, setting my secondary monitor as my primary one resolved the issue. In the mean time I downgraded to version `v13.1.0`.

**Comment by Marcoevich** [comment]
Can confirm, same issue with my 3 monitor setup. Primary monitor is the central monitor. All windows shift to left monitor when making screenshot selection.

**Comment by kirkfriggstadpccu** [comment]
I believe I've got the same issue, also with a 3 monitor setup under Windows 11 24H2 - monitor 1 is laptop screen bottom right at 125% scale, and monitors 2 and 3 top right and left at 100% scale, monitor 2 is set as primary. 

<img width="1012" height="389" alt="Image" src="https://github.com/user-attachments/assets/be8cd3cd-4dbb-4b2f-8be6-284e844d8cef" />

When taking a screenshot in Flameshot, the windows in monitor 2 move to monitor 3, monitor 2 is completely blank, and monitor 1 (underneath monitor 2) is completely black from top to middle of screen. Below the middle of monitor 1, window contents appear normally (not dimmed out like usual for anything outside of the Flameshot capture area). If I change monitor 1 from 125% scale to 100% scale, it goes completely black similar to monitor 2 when taking a screenshot in Flameshot. I'd include a screenshot, but I can't 

Currently running Flameshot 13.3, not sure what version I was running previously but this issue is new since upgrading to 13.3. Downgraded to 12.1, that appears to be working as expected.

Flameshot v13.3.0 (da913d7f)
Compiled with Qt 6.9.2
winnt: 10.0.26100
windows: 11

**Comment by CyberAstronaut101** [comment]
Confirming issue as well, the behavior exactly tracks all previous notes.

Flameshot v13.3.0 (https://github.com/flameshot-org/flameshot/commit/da913d7fe6cb762a794acd4177e9a810e195a598)
Win11 23H2 22631.6199

Reverted to Flameshot v12.1.0 fixed (https://github.com/flameshot-org/flameshot/commit/70be63d478a271da549597d69bd4868607c0a395)

**Comment by zzynx** [comment]
Same problem here with Flameshot v13.3.0 on W11 (25H2 26200.7462)
I had to revert to Flameshot v12.1.0 to fix the problem.

**Comment by maxwxyz** [comment]
Is this the same issue as https://github.com/flameshot-org/flameshot/issues/4172 ?

**Comment by MadWalnut** [comment]
Same issue.

Flameshot 13.3.0
Windows 11 24H2 26100.7171

**Comment by Alistair212** [comment]
Hi I believe I am also encountering the same issue in v13.3.0. I've gone ahead and downloaded past version v13.1.0 and now appears to be working. v13.2 still appeared to have the same issue as 13.3 where the main monitor goes blank, windows decides to switch the main monitor and move my taskbar over...

Tried running as admin, setting full screen compatibility settings on the binary, restoring config to default, reinstalling, updating Nvidia drivers (2060 Super)

Please see the below screen recording of my main (big) and secondary monitor (small). Both are the same scaling and resolution. Weirdly that when I switch my secondary monitor to the main display that screen shotting works correctly and then when switching back it goes back to the incorrect behavior.

https://www.youtube.com/watch?v=7EM1y2JImDY

**Comment by mrorabau** [comment]
I would like to echo that the v13.x.x seem to be broken for multimonitor. Downgrading to Falmeshot-12.1.0-win64.msi works. In my case I have two monitors stacked one on to of the other. Taking a screenshot with flameshot causes the bottom monitor to shift to the top, and what was at the top to disappear. I suspect it has something to do with how windows 11 has changed the way it handles monitor positioning and the new version of flameshot isn't handling it correctly, but the old one seemed to use more legacy libraries which I think windows has kept as backwards compatable.

**Comment by JaneX8** [comment]
I have the exact same issue with Flameshot 13.3.0 installed using Winget on Windows 11 Pro with a three display setup where the middle one is the main display. Its unusable this way indeed. I wanted to downgrade to Flameshot 12.1.0 using Chocolatey but that installer doesn't work. So, on Windows I can't use Flameshot unfortunately. On Linux it works great.

**Comment by Marcoevich** [comment]
> So, on Windows I can't use Flameshot unfortunately.

You can easily use it on Windows by downloading the 12.1.0 release from the releases page here on GitHub. That installer works fine.

**Comment by Caedendi** [comment]
Also experiencing this issue. Right screen shows up on the left monitor, while right screen turns black.
With three monitors, right/middle shift to the screen on the left and the right one is black.

**Comment by borgmanJeremy** [comment]
Solved with #4498

**Comment by yphil05** [comment]
Hi

I am sorry but the problem is still there. It can also be seen in the capture launcher, as it can be seen here:

<img width="830" height="261" alt="Image" src="https://github.com/user-attachments/assets/7a8dae35-9453-4f21-99d0-ec9038e54842" />

Everything is still shifting to the left.  Just to be sure, I've re-started my PC after having installed the last version using snoop:

Flameshot v13.3.0 (da913d7f)
Compiled with Qt 6.9.2
winnt: 10.0.26200
windows: 11
