### ISSUE TITLE
No longer working with multiple screens on Fedora 31

### ISSUE THREAD

**Issue by svelle** [flameshot-org/flameshot#668]
**Flameshot version**
Version      : 0.6.0

**Describe the bug**
Since updating to Fedora 31 flameshot is no longer working with dual monitor setups and wayland. Haven't tested X11. Wenn invoking flameshot with `flameshot gui` it'll capture the whole screen and then left align it on the main window, which renders the applicatio useless because the content of the mainscreen can not be accessed in the overlay. 
Here's a screenshot of the issue: ![Screenshot from 2019-12-05 14-32-36](https://user-images.githubusercontent.com/7526550/70240031-c0656a00-176c-11ea-8a1f-092b14349c8d.png)

**To Reproduce**
Attach second screen to environment call `flameshot gui`.

**Expected behavior**
Captured screenshot gets aligned correctly over all screens.

**System Information**
Fedora 31 GNOME

A workaround for this could be to add a single screen option to flameshot gui and to select only the screen where the mouse cursor is located on by default.

**Comment by Phil-ThePower-Pearce** [comment]
have the same on ubuntu 19.04

**Comment by dgrabla** [comment]
Exactly same issue on Debian 10.2

```
> flameshot --version     
Flameshot 0.6.0-11(Debian)
Compiled with Qt 5.11.3
```

**Comment by ZetaoYang** [comment]
You can make all your QT apps use XWayland:
export QT_QPA_PLATFORM=xcb
Add this to /etc/profile file, then restart.

**Comment by 54sledgehammer45** [comment]
Same problem on OpenSuse tumbleweed

$ flameshot --version
Flameshot v0.6.0
Compiled with Qt 5.14.1

$ lsb_release -a
LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20200307
Codename:       n/a

**Comment by SergeyKons** [comment]
Same problem on Fedora 31
```
$ flameshot --version
Flameshot v0.6.0
Compiled with Qt 5.12.4
```

**Comment by ZetaoYang** [comment]
> Same problem on Fedora 31
> 
> ```
> $ flameshot --version
> Flameshot v0.6.0
> Compiled with Qt 5.12.4
> ```
Here's a compromise solution.
You can make all your QT apps use XWayland:
export QT_QPA_PLATFORM=xcb
Add this to /etc/profile file, then restart.

**Comment by borgmanJeremy** [comment]
@ZetaoYang I think with momentum building on Wayland we probable want to do this without xcb? If so I can add it to our backlog, I was able to confirm it and have a good set up for investigating it.

**Comment by EchoGroot** [comment]
> 您可以使所有QT应用程序都使用XWayland：
> export QT_QPA_PLATFORM = xcb将此
> 添加到/ etc / profile文件中，然后重新启动。

我也遇到了同样的问题，但是使用此方法无效

**Comment by EchoGroot** [comment]
> > 您可以使所有QT应用程序都使用XWayland：
> > export QT_QPA_PLATFORM = xcb将此
> > 添加到/ etc / profile文件中，然后重新启动。
> 
> 我也遇到了同样的问题，但是使用此方法无效

找到原因了，屏幕缩放之前是1.25，就有问题。还原到1.0就正常了

**Comment by Crupuk** [comment]
Any news on this ? 
Still have this issue on Fedora 33 ( wayland ) 

Thx for your help

**Comment by borgmanJeremy** [comment]
This was just fixed in #1282

**Comment by ihipop** [comment]
> > > 您可以使所有QT应用程序都使用XWayland：
> > > export QT_QPA_PLATFORM = xcb将此
> > > 添加到/ etc / profile文件中，然后重新启动。
> > 
> > 
> > 我也遇到了同样的问题，但是使用此方法无效
> 
> 找到原因了，屏幕缩放之前是1.25，就有问题。还原到1.0就正常了

YES, It's because a scale on HiDPI screen. #1282 not fixed this.

@borgmanJeremy
