### ISSUE TITLE
Multiple displays on Windows 10

### ISSUE THREAD

**Issue by szszoke** [flameshot-org/flameshot#739]
**Flameshot version**
0.6.470.0

**Describe the bug**
Multiple display arrangement is not being considered which results in parts of the screenshot overlay pushed off-screen.

Main display: 27'' external screen running at 2560 x 1440, 100% scaling
Secondary display: 15'' laptop screen running at 1920 x 1080, 125% scaling

*Display arrangement that does not cause the issue*
![image](https://user-images.githubusercontent.com/2766129/81297266-4fa3e000-9073-11ea-9380-16e628c602a0.png)

*Display arrangement that triggers the issue*
![image](https://user-images.githubusercontent.com/2766129/81297458-909bf480-9073-11ea-9f9c-364942c98a33.png)

*Before pressing `Print screen` with the triggering display arrangement*
![IMG_20200507_150437](https://user-images.githubusercontent.com/2766129/81297944-57b04f80-9074-11ea-8043-39ec3fec74f0.jpg)

*When the bug is triggered*
![IMG_20200507_150442](https://user-images.githubusercontent.com/2766129/81298004-71519700-9074-11ea-8a90-02831c1c4296.jpg)

*The saved screenshot does not seem to be affected. It seems that it's only the overlays that are drawn from the wrong origin*
![image](https://user-images.githubusercontent.com/2766129/81298190-b4ac0580-9074-11ea-83be-a7e34c612a73.png)

Clicking above the overlays (the part that is not darkened) results in the overlays being closed.

Setting both displays to 1920 x 1080 did not solve the issue.
Changing the scaling did not solve the issue.

The workaround for now is to set up a display arrangement in `Display settings` where the top of each display is aligned, even if they are not in real life.

**To Reproduce**
1. Launch flameshot.exe on a system with a multiple displays.
2. Arrange the displays in `Display settings` so that the tops are not aligned.
3. Press the `Print screen` button on the keyboard.

**Expected behavior**
Screenshot overlay is drawn from the top of the screens regardless of the display arrangement.

**System Information**
Windows 10 Pro 1903 Build 18362.778

**Comment by Tiller** [comment]
hey, it's been annoying me for a couple of month, so I just fixed it. However the project doesn't seem really alive so I doubt it will be merge.
You can found the fix at: https://github.com/lupoDharkael/flameshot/pull/742
There is a fix .exe in the description

**Comment by szszoke** [comment]
That was really quick!

Thanks!

I saw things committed in the past few days, hopefully it will get merged.

**Comment by Martin-Eckleben** [comment]
Maybe has to do with #7 
(oldest issue)

Will definitely look into this!

**Comment by borgmanJeremy** [comment]
I think this is fixed with #1126. @Tiller  your PR actually did fix it so I fixed the merge conflicts and got it committed.

Sorry I missed this PR when I took over or I would have merged sooner.

**Comment by 77erup** [comment]
Not resolved. W11, no matter how do I arrange the screens, still only on one screen (default/main). Whatever, moving to ShareX. 
Thanks for a nice tool. I've been using it for almost 5 weeks.

**Comment by DanielMevit** [comment]
Somehow this same problem reoccurs in the newest Flameshot version v12.1.0 (96c2c82e) on my W10 Home, version: 22H2. 
Let me know if you need anything else from my side.

**Comment by jerry1970** [comment]
I have two screens aligned vertically (external monitor above laptop) and flameshot will only take something from the main (laptop) monitor. The region does not extend on the external monitor and I cannot start a region there either. Quite annoying.

**Comment by nyrahul** [comment]
Faced similar problems in Windows 11 with Flameshot >v13.
Surprisingly didn't face any issues with Flameshot [v12.1.0](https://github.com/flameshot-org/flameshot/releases/tag/v12.1.0).

**Comment by mmahmoudian** [comment]
@ElTh0r0 I wonder if this is reproducible for you and if you have any idea what's happening regarding the last comment and #4152

**Comment by anzy03** [comment]
Facing the same issue. 
Tried with multiple Computers and Different monitor layouts. 
Also tried installing with WinGet and just manually downloading .msi installer.
 
Version info - 
Flameshot v13.1.0 (79395fd3)
Compiled with Qt 6.8.1
winnt: 10.0.26100
windows: 11

**Comment by nyrahul** [comment]
Just as an FYI ... I didn't face the issue with [Flameshot v12.1.0](https://github.com/flameshot-org/flameshot/releases/tag/v12.1.0)

**Comment by steevensk** [comment]
Hi, the issue seems to be back with 13.3.0

**Comment by danielmevit** [comment]
> Hi, the issue seems to be back with 13.3.0

Same here, I'm on Windows 11 Pro, version 25H2. I ended up disabling the app because I can't make proper screenshots anymore. If there's anything I can help with, let me know!

**Comment by steevensk** [comment]
It seem, that (at least in my case) the issue is present only in case the Scale of the two monitors is different; e.g. External (main) 125%, Laptop 100%. It works without issues if both are set to the same scale; e.g. both 100% or both 125%. 

<img width="4286" height="1621" alt="Image" src="https://github.com/user-attachments/assets/677c1f42-ee59-4f79-959a-f34e443574d9" />

**Comment by bencorryp** [comment]
Unfortunately can confirm that monitor scale is not the only factor - mine are both set to 100% and the issue persists.

**Comment by MrCaringi** [comment]
Same issue on Windows11 with Flameshot v13.3.0 (da913d7f)

Any idea how to solve this?

**Comment by julianluongo** [comment]
Can confirm, with the latest 13.3.0 the issue is present, but with v12.1.0 works perfectly! what might it be? I have two 1080p monitors in vertical.
