### ISSUE TITLE
FlameShot doesn't start, no errors

### ISSUE THREAD

**Issue by Ulrar** [flameshot-org/flameshot#90]
Hi,

I've installed flameshot on gentoo from the jorgicio overlay. When I type "flameshot" in a term, it just hangs forever. If I try the gui, full or config options, it immediately exits without any output (return code is 0). I tried starting dbus, see if that helps, but no changes.

Is there a debug mode, or something I could try to see what the problem might be ?

**Comment by lupoDharkael** [comment]
A friend just notified the same situation. I'll talk with him and see if I can find the problem.

**Comment by alexanderadam** [comment]
Having the same issues. But calling `flameshot gui` shows something.

**Comment by WhyNotHugo** [comment]
I've the exact same issue:

* `flameshot` just idles immediately.
* `flameshot gui` exists immediately (exit code `0`).
* `flameshot config` exists immediately (exit code `0`).

Most importantly, the screenshot *is not* saved. I'm running ArchLinux, with Xorg/i3wm. I'm using the [AUR package](https://aur.archlinux.org/packages/flameshot/).

I'm happy to provide extra information as required.

**Comment by zingmars** [comment]
Same issue here. I'm running KDE Neon, and installed Flameshot using the .deb package meant for Ubuntu Xenial (16.04) from the Releases.

**Comment by PhilsLab** [comment]
I'm having a similar issue; running flameshot from the terminal works as expected, but via rofi menu the application doesn't show up at all.
(Is this an environment issue maybe?)

**Comment by tkkcc** [comment]
Use `exec dbus-launch i3` instead of `exec i3` in `~/.xinitrc` works. Get from #168

I use i3wm(4.15), after my first installation of flameshot, `flameshot gui` works, but after reboot it exists immediately with exit code 0, then I switch to xfce4(edit .xinitrc and i3 exit), it works, then I switch to i3 (edit .xinitrc and pkill Xorg), it works too.

**Comment by Pandentia** [comment]
This issue is also happening to me on NixOS in KDE Plasma 5, with FlameShot 0.5.1 (from both the latest release and unstable repositories).

**Comment by derekwsgray** [comment]
Worked when I installed it. Now I only get this problem. Just doesn't start, no errors.

**Comment by polishExperiment** [comment]
I'm on Ubuntu 18.04. When I press Prt Scr the screenshot is taken but it is taken by native ubuntu screen capture tool, I presume - it is saved in Pictures directory with name such as "Screenshot from 2018-09-25 13-47-09.png". But flametool does nothing. It's icon just sits there in the top bar next to battery indicator.

**Comment by WhyNotHugo** [comment]
Still not working for me on Archlinux, using flameshot 0.6.0:

```
$ flameshot  # Idles indefinitely
QApplication: invalid style override passed, ignoring it.

$ flameshot gui  # Exists immediately

$ flameshot full
Invalid format, set where to save the content with one of the following flags:
 -p, --path
 -r, --raw
 -c, --clipboard

Usage: flameshot full [full-options]

Options:
  -p, --path <path>           Path where the capture will be saved
  -c, --clipboard             Save the capture to the clipboard
  -d, --delay <milliseconds>  Delay time in milliseconds
  -r, --raw                   Print raw PNG capture
  -h, --help                  Displays this help

$ flameshot config  # Exits immediately
```

**Comment by sgse** [comment]
On Manjaro Xfce, Kernel 4.19 no tray-icon.
From terminal
```
~ >>> flameshot
qt5ct: using qt5ct plugin     - Did not start

~ >>> flameshot gui          - start

~ >>> flameshot full
Invalid format, set where to save the content with one of the following flags:
 -p, --path
 -r, --raw
 -c, --clipboard

Usage: flameshot full [full-options] 

Options:
  -p, --path <path>           Path where the capture will be saved
  -c, --clipboard             Save the capture to the clipboard
  -d, --delay <milliseconds>  Delay time in milliseconds
  -r, --raw                   Print raw PNG capture
  -h, --help                  Displays this help

~ >>> flameshot config     - start
```
![grafik](https://user-images.githubusercontent.com/17575778/46943025-fb8b7200-d06e-11e8-9e00-f5da7e580dc0.png)

**Comment by sgse** [comment]
Work with gtk3-classic
![2018-10-15-12-02-32](https://user-images.githubusercontent.com/17575778/46944581-b701d580-d072-11e8-990a-fe7715f587bd.png)


![work-2018-10-15-11-57-57](https://user-images.githubusercontent.com/17575778/46944539-98034380-d072-11e8-8abe-df876c5322a0.png)

**Comment by kylescousin** [comment]
Had the same issue, but when manually adding flameshot to the system tray it worked.

**Comment by rod-stuchi** [comment]
Same issue here, I'm running Arch 4.18.5-arch1, with i3 4.16 and Flameshot 0.6.0-1 (via community).
It opens but not showing gui, but the process still running.

**Comment by christianmtr** [comment]
I just comment my case in other similar issue.
https://github.com/lupoDharkael/flameshot/issues/403#issuecomment-441126951

**Comment by juancampa** [comment]
This is happening to me if I have two X servers running locally. It will show in the wrong one. It's like flameshot is not paying attention to the `DISPLAY` environment variable

**Comment by rubenbarreiro** [comment]
happening to me as well. was working normal since the first install, then couple days ago just doesn't launch as well. I'm using linux mint 19.1 cinnamon edition

**Comment by genejr** [comment]
Ubunut 18 getting exact behaviour WhyNotHugo saw...

$ flameshot  # Idles indefinitely
QApplication: invalid style override passed, ignoring it.

$ flameshot gui  # Exists immediately

$ flameshot full
Invalid format, set where to save the content with one of the following flags:
 -p, --path
 -r, --raw
 -c, --clipboard

Usage: flameshot full [full-options]

Options:
  -p, --path <path>           Path where the capture will be saved
  -c, --clipboard             Save the capture to the clipboard
  -d, --delay <milliseconds>  Delay time in milliseconds
  -r, --raw                   Print raw PNG capture
  -h, --help                  Displays this help

$ flameshot config  # Exits immediately

**Comment by dNvl** [comment]
Using Ubuntu 18.04LTS with the 4.19 LTS Kernel and Gnome. Stopped working about a week ago. Same issues as @genejr

**Comment by mitchellkrogza** [comment]
Same problem on Manjaro Cinnamon, worked after installation but after a reboot (some 14 days later) it no longer works.

**Comment by Alexxz** [comment]
Ubuntu Disco Dingo (development branch) default desktop 
Started as `flameshot` just waits for something and no notification icon in system tray.
Started as `flameshot gui` shows a selection interface and seems to be functional. 

So it is possible to continue using it but every time I need to start it as a separate command 8(

**Comment by NikosAlexandris** [comment]
Under `Linux version 4.18.16-gentoo-FC.01 (root@carbon) (gcc version 7.3.1 20180703 (Funtoo 7.3.1-r3)) #1 SMP Sun Nov 4 13:25:44 CET 2018` and  i3 (4.14.1):

```
flameshot
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
qt5ct: custom style sheet is disabled
```
> [Screenhot](https://i.imgur.com/4ddlJ2E.png), [Icon in i3wm](https://i.imgur.com/XvdoJoQ.png)

The icon is usable and I can use the tool.  The rest, however, do not work. In example:
```
flameshot gui |echo $?
0
```
and the same for
```
flameshot full --path ~
```
and
```
flameshot screen --path ~
```
do nothing.

**Comment by xRiot** [comment]
Bumping this report, I encounter the same issue as described above on Debian Buster using KDE Plasma 5.

**Comment by xcme** [comment]
The same issue on Manjaro Cinnamon,
The "/usr/bin/flameshot gui" works but just "/usr/bin/flameshot" doesn't work.

**Comment by mihai-dinu** [comment]
In my case, I had another flameshot instance running in the background without me knowing it (the autostarted flameshot instance). Killed that instance and started it again and now it works.

If you want flameshot to autostart correctly at login, then modify `~/.config/autostart/Flameshot.desktop` to contain: `Exec=/bin/bash -c "sleep 10; flameshot &"` instead of the regular `Exec`

**Comment by mitchellkrogza** [comment]
@mihai-dinu you sir are a genius :clap: this indeed works 100% .... finally I have flameshot back without having to keep triggering it via command line. :clap:

**Comment by NikosAlexandris** [comment]
> Exec=/bin/bash -c "sleep 10; flameshot &"

Which OS? Does not work for me.

**Comment by NikosAlexandris** [comment]
> **Edit:** I resolved this by resetting my locales _(since my system wasn't able to locate LC_ALL)_ and desktop launch option. Go to: `System Settings > Regional Settings > Reset all` and then set desktop launcher to `Exec=flameshot gui` in `/usr/share/applications/flameshot.desktop`.

How is this important? Here my locales, all set:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
```

**Comment by MarvinFS** [comment]
> If you want flameshot to autostart correctly at login, then modify `~/.config/autostart/Flameshot.desktop` to contain: `Exec=/bin/bash -c "sleep 10; flameshot &"` instead of the regular `Exec`

works for me either! manjaro latest release

**Comment by mihai-dinu** [comment]
@NikosAlexandris I'm using Solus, but that command should work for any distro. Try the command in a terminal and see if that works. If it does, then it's probably something with the way the ".desktop" files are interpreted for your distro.

**Comment by NikosAlexandris** [comment]
> @NikosAlexandris I'm using Solus, but that command should work for any distro. Try the command in a terminal and see if that works. If it does, then it's probably something with the way the ".desktop" files are interpreted for your distro.

I think I misunderstood. Your solution solves the problem of not being able to launch flameshot (gui) at all.  The issue(s) I observe is that I cannot run any of:
```
flameshot gui
```
and
```
flameshot full --path ~
```
and
```
flameshot screen --path ~
```
while simply running `flameshot` does open the GUI. A delay of the execution (i.e. `sleep 10`) of `flameshot` is not changing anything here.

**Comment by mitchellkrogza** [comment]
Did you make sure you commented out the original Exec? @NikosAlexandris @MarvinFS mine is working with this fix on Latest Manjaro Cinnamon ... must reboot after this change.
```

[Desktop Entry]
Name=flameshot
Icon=flameshot
#Exec=flameshot
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
Exec=/bin/bash -c "sleep 10; flameshot &"
```

**Comment by NikosAlexandris** [comment]
> Did you make sure you commented out the original Exec? @NikosAlexandris @MarvinFS mine is working with this fix on Latest Manjaro Cinnamon ... must reboot after this change.
> 
> ```
> 
> [Desktop Entry]
> Name=flameshot
> Icon=flameshot
> #Exec=flameshot
> Terminal=false
> Type=Application
> X-GNOME-Autostart-enabled=true
> Exec=/bin/bash -c "sleep 10; flameshot &"
> ```

Thank you. Can you please post the output of the three following commands, executed in the command line?
```
flameshot gui |echo $?
flameshot full --path ~ |echo $?
flameshot screen --path ~ |echo $?
```

**Comment by mitchellkrogza** [comment]
```
$ flameshot gui |echo $?
0
$ flameshot full --path ~ |echo $?
0
$ flameshot screen --path ~ |echo $?
0
```

**Comment by NikosAlexandris** [comment]
> ```
> $ flameshot gui |echo $?
> 0
> $ flameshot full --path ~ |echo $?
> 0
> $ flameshot screen --path ~ |echo $?
> 0
> ```

This means that if you do
```
flameshot full --path ~
```
there is no screenshot saved in your home directory. Which means, none of the above three work for you either in the command line. Which is the issue. See also posts above from @tkkcc and @WhyNotHugo. Though @tkkcc managed to solve the problem for working under `i3` (under which I work too).

**Comment by NikosAlexandris** [comment]
> Use `exec dbus-launch i3` instead of `exec i3` in `~/.xinitrc` works. Get from #168
> I use i3wm(4.15)

@tkkcc, is the file `/etc/X11/Sessions/i3wm` related?
It contains
```
#!/bin/sh
exec /usr/bin/i3
```

I edited this by adding the`dbus-launch` part, but no luck.

**Comment by tkkcc** [comment]
@NikosAlexandris Sorry, I am now using flameshot without any trick, though I don't know why it broke before. My version is `flameshot 0.6.0-3, i3-wm 4.16.1-1`, I run `startx` in my login shell, and has these in `xinitrc`
```sh
flameshot >/dev/null 2>&1&
exec i3
```
then in i3, run `flameshot gui` works

**Comment by NikosAlexandris** [comment]
Interesting, if I do in the command line exactly
> ```shell
> flameshot >/dev/null 2>&1&
> ```

the following works then too:
```
flameshot full --path ~
```
and saves a screenshot as expected under ~.

Perhaps I misunderstood the way it is supposed to work. I am thinking of `flameshot` as a command line utility (too), which I can use at any given point within from any terminal.  Without the need to have it run on the background.
?

**Comment by hugollsouza** [comment]
I use flameshot on Kali Linux and it does not start when I click the icon in Dash to Dock, I'm using Gnome Shell. I installed the main menu package (apt install alacarte), I edited the flameshot icon and I added the gui at the end of the command.
![2019-04-14_06-36](https://user-images.githubusercontent.com/5652137/56091017-b7dbbe80-5e7f-11e9-8d70-2f456f5c3ed1.png)

**Comment by Raj2032** [comment]
Same thing it doesn't even launch in either ArchLabs (based on Arch Linux) and Zorin OS (based on Ubuntu) What is going on?

**Comment by mitchellkrogza** [comment]
@Raj2032 did you try the `Exec` fix in `~/.config/autostart/Flameshot.desktop` ?

```
[Desktop Entry]
Name=flameshot
Icon=flameshot
Exec=/bin/bash -c "sleep 10; flameshot &"
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
```

**Comment by Raj2032** [comment]
It turns out that I am having dependency issues, it for some reason installed in GUI but I tried to launch it nothing happens but using terminal I am getting dependency errors. I am kinda new to the Linux world so I need to understand better how do I fix dependency issues?

I believe I have to type `sudo apt-get install -f` to fix any broken dependency. then what am I supposed to do next?

**Comment by zeddock** [comment]
I am on Linux Mint 19.1.
On initial install everything works and icon sits nicely in Notification try ready to be used.
But after reboot, it is not loaded.

I got some help and several different things were attempted:
dbus-launch flameshot &
and
dbus-launch flameshot gui &

**But this above suggestion is what worked for me as well:**
In autostart I changed the exec= line to read: Exec=/bin/bash -c "sleep 10; flameshot &"

However, I also noticed 2 other things that seem to make a difference:
1. If you toggle the checkbox in the Flameshot config for startup, it puts another entry into autostart which seems to gum things up
2. You have to right-click or otherwise set the new entry to Trusted.

zeddock

**Comment by derekwsgray** [comment]
Thanks! That worked for me!

> I got some help and several different things were attempted:
> dbus-launch flameshot &
> **But this above suggestion is what worked for me as well:**
> In autostart I changed the exec= line to read: Exec=/bin/bash -c "sleep 10; flameshot &"

> 
> zeddock

**Comment by zeddock** [comment]
Please do keep in mind that the version available to normal users on Linux Mint 19.1 is still version 5.
I am attempting to update mine now to version 6, and hoping to get that all-desired TEXT tool working with it!
This is a great tool!  If you are coming to Linux from Windows, please donate to support this tool. I don't know the creator or any of the fine folks helping to develop and extend it, but if we want a good tool like this to keep going donations speak loudly!

Good luck to you!

**Comment by Kreyren** [comment]
Same issue here, starting `flameshot` fixed the issue -> suggesting error message for this scenario.

**Comment by Neasden** [comment]
I came across this problem, observing Ubuntu and Fedora 30. What happens is that, in Ubuntu, when you start Flameshot, it starts basically as an minimized icon in Ubuntu's customized GNOME Shell tray, from there, you can take screenshots. I also noticed that Telegram Desktop had its icon being displayed in Ubuntu's notifications tray.

So, we have this situation of GNOME Shell Vanilla not displaying the tray icons for these applications, because I noticed that neither Telegram or Flameshot would appear in F30 up to date as of today. Although Telegram will run and appear in the dash and the window will open, Flameshot, as it is designed, needs a small tweak, until GNOME or Flameshot dude works out a way. I read somewhere that GNOME don't want app icons in its tray anymore. Now, I can't remember where I read that -- but coming from GNOME, that is completely believable.

My fix was to edit:
`sudo /usr/share/applications/flameshot.desktop`

and in 
`[Desktop Entry]`
append the gui to the line of Exec=flameshot

`Exec=flameshot`

to

`Exec=flameshot gui`

There are other entires but I don't know how they work.
After saving the file I was able to run Flameshot both in Wayland and Xorg.

**Comment by Kreyren** [comment]
> Exec=flameshot -> Exec=flameshot gui

Doesn't work on my end since based on provided informations `flameshot` has to be running for `flameshot gui` to open a GUI.

**Comment by Neasden** [comment]
Okay. I see. Looks like the developer needs to circumvent ways to avoid flameshot to start minimized, plus, I think your case is different. Operating system I tested this were Ubuntu 19.04 and Fedora 30.

**Comment by benjaminbauer** [comment]
> > Exec=flameshot -> Exec=flameshot gui
> 
> Doesn't work on my end since based on provided informations `flameshot` has to be running for `flameshot gui` to open a GUI.

Same here on Ubuntu 18.04
```
Flameshot 0.5.1-1(Debian)
Compiled with QT 5.9.4
```

**Comment by NikosAlexandris** [comment]
> Interesting, if I do in the command line exactly
> 
> > ```shell
> > flameshot >/dev/null 2>&1&
> > ```
> 
> the following works then too:
> 
> ```
> flameshot full --path ~
> ```
> 
> and saves a screenshot as expected under ~.
> 
> Perhaps I misunderstood the way it is supposed to work. I am thinking of `flameshot` as a command line utility (too), which I can use at any given point within from any terminal. Without the need to have it run on the background.
> ?

BUMP. Is `flameshot` thought to be a command line tool as well as a GUI-based tool, or only the latter?

Thank you.

**Comment by codingtalkie** [comment]
using MXLinux 19 
$ flameshot 
Icon theme "Numix-Circle-Light" not found.
...
thats all, FlameShot is not opening after 30 minutes, still showing that message

**Comment by marcmorente** [comment]
I fix it editing the file `flameshot.desktop`

`sudo nano /usr/share/applications/flameshot.desktop` and change 

```
[Desktop Entry]
Exec=flameshot
```

by

```
[Desktop Entry]
Exec=flameshot gui
```

**Comment by mbacilieri** [comment]
Hallo.

Same issue here, Ubuntu 18.04.
On 16.04 worked flawlessy. After upgrade, it doesn't start with no error.
A ps -aux | grep flameshot shows a process running, but no gui opens.
Adding gui or config to the command line, the gui or the config forms open. Although there's no way to start a "normal" session.

**Comment by Sun1ive** [comment]
Same here Archlinux latest

**Comment by realForbis** [comment]
1. Go to settings
2. Devices
3. Keyboard Shortcuts
4. set Custom Shortcut
![image](https://user-images.githubusercontent.com/37193612/69919513-c6fa9580-147d-11ea-9a40-bea03767b233.png)
Done!

**Comment by algiuxass** [comment]
What did help me was running "flameshot" and then "flameshot gui" while "flameshot" is still running in the background

**Comment by rahatzamancse** [comment]
Same problem (flameshot does nothing)
- bspwm
- gtk3 installed

**Comment by realForbis** [comment]
You need to "bind" it to some "key" on the keyboard

**Comment by marcelodufe** [comment]
Same issue on arch + i3

**Comment by amassarwi** [comment]
> I came across this problem, observing Ubuntu and Fedora 30. What happens is that, in Ubuntu, when you start Flameshot, it starts basically as a minimized icon in Ubuntu's customized GNOME Shell tray, from there, you can take screenshots. I also noticed that Telegram Desktop had its icon being displayed in Ubuntu's notifications tray.
> 
> So, we have this situation of GNOME Shell Vanilla not displaying the tray icons for these applications, because I noticed that neither Telegram nor Flameshot would appear in F30, up to date, as of today. Although Telegram will run and appear in the dash and the window will open, Flameshot, as it is designed, needs a small tweak, until GNOME or Flameshot dude works out a way. I read somewhere that GNOME don't want app icons in its tray anymore. Now, I can't remember where I read that -- but coming from GNOME, that is completely believable.
> 
> My fix was to edit:
> `sudo /usr/share/applications/flameshot.desktop`
> 
> and in
> `[Desktop Entry]`
> append the gui to the line of Exec=flameshot
> 
> `Exec=flameshot`
> 
> to
> 
> `Exec=flameshot gui`
> 
> There are other entires but I don't know how they work.
> After saving the file I was able to run Flameshot both in Wayland and Xorg.
Fixed my issue on debian kde
+1 :tada:

**Comment by damsma** [comment]
On Debian 10 you have to install gnome-shell-extension-appindicator
`sudo apt install gnome-shell-extension-appindicator gnome-tweaks`

then log out and log in again, open up Gnome tweaks and enable "Kstatusnotifieritem/appindicator support"

in terminal type

`flameshot config`

and under general click on "Show tray icon"

![grafik](https://user-images.githubusercontent.com/45398732/75904445-837c4280-5e43-11ea-94b2-2aabbc00915f.png)

**Comment by rollto** [comment]
After install gnome-shell-extension-appindicator gnome-tweaks, even can not login to desktop.

**Comment by rollto** [comment]
Cannot login into GNOME, kicking me back to login screen 
after apt install gnome-shell-extension-appindicator gnome-tweaks

**Comment by damsma** [comment]
> Cannot login into GNOME, kicking me back to login screen
> after apt install gnome-shell-extension-appindicator gnome-tweaks

i don't think this is because of installing gnome tweaks, maybe you tried to reconfigure Xorg before and something went wrong?
have you tried reverting your steps? checked the logs?
i've done this on 3 fresh installed debian 10 machines and none of them had this issue.

**Comment by rollto** [comment]
Flameshot is good application , 
definitely it was that gnome-shell-extension-appindicator gnome-tweaks corrupt my gnome desktop environment .
I can only login xfce4 mate lxqt,lxde now,can not use gnome anymore,  
tried chown .Xauthority no luck. 

ls /usr/bin/*session
/usr/bin/cinnamon-session              /usr/bin/lxqt-session
/usr/bin/dbus-run-session              /usr/bin/lxsession
/usr/bin/gnome-session                 /usr/bin/mate-session
/usr/bin/gnome-session-custom-session  /usr/bin/openbox-session
/usr/bin/lxqt-config-session           /usr/bin/xfce4-session

**Comment by ianseyer** [comment]
Running arch. Using i3.

When trying to run flameshot, was getting:
`Cannot mix incompatible Qt library (version 0x50d02) with this library (version 0x50e01)`

Used `yay` to reinstall qt-5 libs.

Now I am getting this behavior. Not sure if that precursor helps.

**Comment by JakeRoggenbuck** [comment]
I had this same issue after trying to save the screenshot as a file. I am using bspwm and flameshot just dose not open after I re install of flameshot or a reboot.

**Comment by udhien80** [comment]
> In my case, I had another flameshot instance running in the background without me knowing it (the autostarted flameshot instance). Killed that instance and started it again and now it works.
> 
> If you want flameshot to autostart correctly at login, then modify `~/.config/autostart/Flameshot.desktop` to contain: `Exec=/bin/bash -c "sleep 10; flameshot &"` instead of the regular `Exec`

Thank you very much, it works for me.

TPX220-i7-16G-DualSSD(160G+250G)-LMDE4

**Comment by rmo20** [comment]
Executing
```
$ flameshot &
$ flameshot gui
```
solves the problem, but is this the only way to get `flameshot` to work correctly? Why is this happening? This isn't common behavior of other screen captures (e.g. `scrot`, `gnome-screenshot`, etc.)

**Comment by alexanderadam** [comment]
> Executing
> 
> ```
> $ flameshot &
> $ flameshot gui
> ```
> 
> solves the problem

indeed! I changed my shortcut now to:

```bash
/usr/bin/flameshot & bash -c "sleep 1 && /usr/bin/flameshot gui"
```

**Comment by codingtalkie** [comment]
>     1. Go to settings
> 
>     2. Devices
> 
>     3. Keyboard Shortcuts
> 
>     4. Set Custom Shortcut
>        ![image](https://user-images.githubusercontent.com/37193612/69919513-c6fa9580-147d-11ea-9a40-bea03767b233.png)
>        Done!

I confirm, this work well on MXLinux 19. now the flameshot is working

**Comment by w4r0** [comment]
> .config

I confirm this, this work as well on Mint 19.3 Cinnamon.

**Comment by w4r0** [comment]
> In my case, I had another flameshot instance running in the background without me knowing it (the autostarted flameshot instance). Killed that instance and started it again and now it works.
> 
> If you want flameshot to autostart correctly at login, then modify `~/.config/autostart/Flameshot.desktop` to contain: `Exec=/bin/bash -c "sleep 10; flameshot &"` instead of the regular `Exec`

I confirm this, this work as well on Mint 19.3 Cinnamon.

**Comment by gdsouza1** [comment]
Had the same issue on ArchLinux 5.7.6-zen  running bspwm and X, it only works after running
`flameshot &`, then the other commands work, like `flameshot gui`, added it to bspwmrc to start with the WM and all works fine.

**Comment by diego-aquino** [comment]
I had the same issue trying to open Flameshot via terminal with `flameshot` or by clicking the app icon. Running `flameshot gui` works fine, though.

**Comment by tmccombs** [comment]
For me `flameshot` and `flameshot config` work fine, but `flameshot gui` immediately exits with a 0 status code and no error message. Is there any verbose option to print more information on what is going on?

**Comment by laurindofljunior** [comment]
Hey guys.
I have the same problem. My flameshot don't open when I click it in the applications list.
To fix it I changed my config to this:

```
[Desktop Entry]
Exec=flameshot gui --delay 1000
```

Adding the delay parameter, flameshot works correctly to me.
Hope this helps!

**Comment by weilbith** [comment]
@laurindofljunior so you get then the "gui" after the delay? Because for me the command does nothing and then exists after the delay...

**Comment by laurindofljunior** [comment]
Hi @weilbith . I put it this before the "delay". You can test the command in the terminal. Open the terminal and try the command please:

`flameshot gui --delay 1000`

This command is the same that I use in my file 'flameshot.desktop'.

**Comment by weilbith** [comment]
That is exactly what I did. :smile:

**Comment by laurindofljunior** [comment]
> That is exactly what I did. 😄

@weilbith I understand that you put the command after the "--delay" and not before like me.  😄 😄 
I read it in your message at 10/09/2020.

**Comment by tmccombs** [comment]
`flameshot gui --delay 1000` did not work for me at one point, but `flameshot gui` itself seems to be hit-or-miss for me. Sometimes it works, sometimes it doesn't, and haven't been able to figure out a pattern for when it doesn't work.

**Comment by Nightowlswing** [comment]
Fixed problem with `sudo apt install git g++ build-essential qt5-qmake qt5-default qttools5-dev-tools` on Ubuntu 20.04

**Comment by bazhil** [comment]
After update Flameshot dont run and dont shows in taskbar. Ubuntu 20.04. Before that use it without problems. Reinstall dont helps. How fix this? Need Flameshot for work.

**Comment by letdowntown** [comment]
Same problem as @bazhil. The only way I can use Flameshot is by running `flameshot gui`. Clicking on the app icon does nothing, and running `flameshot` just prints `qt5ct: using qt5ct plugin`.

**Comment by borgmanJeremy** [comment]
@bazhil @letdowntown can you open a new issue and post all the information from the issue template?

**Comment by ctrl-f5** [comment]
also had this problem on ubuntu, found the solution here: https://github.com/flameshot-org/flameshot/issues/1261

- remove from startup applications
- make sure running process is killed
- start flameshot manually

**Comment by borgmanJeremy** [comment]
I'm going to close this thread as it has many many many different issues wrapped up in it that span many years. Many of these issues have been solved over time.

**Comment by xueyubingsen** [comment]
> > In my case, I had another flameshot instance running in the background without me knowing it (the autostarted flameshot instance). Killed that instance and started it again and now it works.
> > If you want flameshot to autostart correctly at login, then modify `~/.config/autostart/Flameshot.desktop` to contain: `Exec=/bin/bash -c "sleep 10; flameshot &"` instead of the regular `Exec`
> 
> Thank you very much, it works for me.
> 
> TPX220-i7-16G-DualSSD(160G+250G)-LMDE4

Thank you very much, it works for me.

**Comment by noopurphalak** [comment]
> Fixed problem with `sudo apt install git g++ build-essential qt5-qmake qt5-default qttools5-dev-tools` on Ubuntu 20.04

Does not work...

**Comment by mmahmoudian** [comment]
@noopurphalak this issue is closed. If you are facing issues with the newest Flameshot version (right now it is v0.9.0), please open a new issue and provide detailed information so that we can investigate it.

**Comment by mmahmoudian** [comment]
@hanhpv @cvanelteren

If you are facing some issues with Flameshot, I strongly recommend you to open a proper bug report issue and participate in solving the issue, as despite the myth, unfortunately downvoting my comments wouldn't make the bugs disappear on your computer 😉

**Comment by cvanelteren** [comment]
@mmahmoudian  I did that on april 12th (see [here]( https://github.com/flameshot-org/flameshot/issues/1553) ). I am happy to provide additional info in addition to the logs provided in that thread.

**Comment by Lime365** [comment]
Linux Manjaro Gnome 40.1.0
Had the same issue when installing via snap.
Issue was solved when i removed from snap and installed via pacman (Add/Remove Software)

**Comment by normic** [comment]
> ```
> [Desktop Entry]
> Exec=flameshot gui --delay 1000
> ```
Sounds good, but at least on Linux Mint 19 this does not solve the autostart issue. Instead it gives the option to take a screenshot even before the desktop is fully loaded.

**Comment by Rishi-jha** [comment]
You can change the exec to flameshot laucher in /usr/share/applications/flameshot.desktop

```
Keywords[es]=flameshot;screenshot;capture;shutter;captura;
Exec=flameshot launcher
Icon=flameshot
Terminal=false
Type=Application
Categories=Graphics;
```

**Comment by pesekviktor** [comment]
When I start flameshot from the terminal I get 
`QDBusTrayIcon encountered a D-Bus error: QDBusError("org.gnome.gjs.JSError.ValueError", "domain.replaceAll is not a function")
`

Running flameshot-gui works.

I am on Ubuntu 20.04.5 LTS. 

Would anyone know how to fix it?

**Comment by eightys3v3n** [comment]
Adding a note for other people and myself in the future. Hopefully, this doesn't notify a bunch of people.
I had similar behaviour and the issue was flameshot was opening on an unplugged display.
Not a flameshot issue but try `xrandr --auto` to _unplug_ the 2nd display.

**Comment by pesekviktor** [comment]
Unfortunately that did not work for me....

**Comment by lukinhas711** [comment]
Hi, I fixed my problem just by uninstalling and installing the `.deb` version after I added the custom shortcut.

**Comment by mahelo1985** [comment]
I had this issue under Debian 11 with GNOME 3.38.5 and Wayland as Window Manager. After I installed the latest Version of flameshot from github.com, nothing happens when I clicked on the desktop icon.

At first, I executed `flameshot` in the terminal. The output was the error message `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

In addition, `flameshot gui` opens the screenshot tool of GNOME.

I fixed this by disabling Wayland in /etc/gdm3/daemon.conf, by adding `QT_QPA_PLATFORM=xcb` in /etc/environment and restarting the machine. The workaround can be found on [stackoverflow.com](https://stackoverflow.com/questions/69828508/warning-ignoring-xdg-session-type-wayland-on-gnome-use-qt-qpa-platform-wayland).

**Further Keyboard Settings:**

- I changed the shortcut [PRINT] under GNOME Settings -> Keyboard Shortcuts. 
- I copied the desktop app config with `cp /usr/share/applications/org.flameshot.Flameshot.desktop .local/share/applications` in my home directory and adapted the entry `Exec=/usr/bin/flameshot` to `Exec=/usr/bin/flameshot gui --delay 500`.

**Comment by mmahmoudian** [comment]
@mahelo1985 

In addition, flameshot gui opens the screenshot tool of GNOME.

If you mean the window with the "Share" button, then that's how Gnome works. Read more here:

https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time

**Comment by ArtemSam86** [comment]
**Subject: Flameshot fails to capture screen on Ubuntu 25.10 - "Unable to capture screen" error**

Hello,

I'm experiencing a persistent issue with Flameshot on Ubuntu 25.10 where it fails to capture the screen. When I try to take a screenshot, I get the following error:

```
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
flameshot: info: Screenshot aborted.
```

**Environment:**
- OS: Ubuntu 25.10
- Display Server: Wayland (default)
- Flameshot version:
Flameshot v13.3.0 (88c951e7)
Compiled with Qt 6.4.2

**What I've tried:**
- Launching with `QT_QPA_PLATFORM=wayland flameshot gui`
- Switching to Xorg session (this works, but I need Wayland compatibility)
- Reinstalling Flameshot
- Checking configuration settings

The error occurs consistently when trying to capture the screen in Wayland session. The application starts, shows the interface, but cannot actually capture the screen content.

Has anyone encountered this issue or can suggest additional troubleshooting steps? I'd appreciate any guidance on making Flameshot work properly with Wayland.

Thank you!

---
*You can fill in the Flameshot version after running `flameshot --version` in terminal. This message provides all the essential information the community would need to help diagnose the issue.*

**Comment by olafdietsche** [comment]
Disclaimer: I understand that Wayland is special and I don't have any experience with Wayland.

Searching for "wayland screenshot" leads among others to [watershot](https://github.com/Kirottu/watershot)

> A simple wayland native screenshot tool inspired by Flameshot.

Maybe this is an alternative for your setup.

**Comment by mmahmoudian** [comment]
@ArtemSam86 it have been reported that rebooting the system right after updating Flameshot have helped in resolving that issue on both KDE Plasma and Gnome sessions. Have you tried that? If it persists, please open a new bug report. And tag me. Thanks.

**Comment by ArtemSam86** [comment]
@mmahmoudian The problem was solved in the following way. The method you indicated did not help.

<img width="980" height="476" alt="Image" src="https://github.com/user-attachments/assets/2833ec0c-df2a-4c5d-93bc-28c54bc5f4cd" />

**Comment by ArtemSam86** [comment]
Here's a hint https://github.com/flameshot-org/flameshot/issues/4349
